### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '5rc1'

### ISSUE THREAD

**Issue by QiFuChina** [neonbjb/tortoise-tts#103]
After I install and run command `python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast` , it shows result like this:
```Traceback (most recent call last):
  File "tortoise/do_tts.py", line 7, in <module>
    from api import TextToSpeech, MODELS_DIR
  File "E:\ResourceCode\tortoise-tts\tortoise\api.py", line 22, in <module>
    from tortoise.utils.audio import wav_to_univnet_mel, denormalize_tacotron_mel
  File "C:\DevelopmentProgram\anaconda3\envs\tortts\lib\site-packages\tortoise-2.4.2-py3.8.egg\tortoise\utils\audio.py", line 4, in <module>
    import librosa
  File "C:\DevelopmentProgram\anaconda3\envs\tortts\lib\site-packages\librosa\__init__.py", line 209, in <module>
    from . import core
  File "C:\DevelopmentProgram\anaconda3\envs\tortts\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\DevelopmentProgram\anaconda3\envs\tortts\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "C:\DevelopmentProgram\anaconda3\envs\tortts\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "C:\DevelopmentProgram\anaconda3\envs\tortts\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\DevelopmentProgram\anaconda3\envs\tortts\lib\site-packages\librosa\util\utils.py", line 9, in <module>
    import numba
  File "C:\DevelopmentProgram\anaconda3\envs\tortts\lib\site-packages\numba\__init__.py", line 20, in <module>
    from numba.core import types, errors
  File "C:\DevelopmentProgram\anaconda3\envs\tortts\lib\site-packages\numba\core\types\__init__.py", line 7, in <module>
    from .containers import *
  File "C:\DevelopmentProgram\anaconda3\envs\tortts\lib\site-packages\numba\core\types\containers.py", line 17, in <module>
    from .common import (
  File "C:\DevelopmentProgram\anaconda3\envs\tortts\lib\site-packages\numba\core\types\common.py", line 6, in <module>
    from numba.core.errors import NumbaTypeError, NumbaValueError
  File "C:\DevelopmentProgram\anaconda3\envs\tortts\lib\site-packages\numba\core\errors.py", line 171, in <module>
    if tuple([int(x) for x in colorama_version.split('.')]) < (0, 3, 9):
  File "C:\DevelopmentProgram\anaconda3\envs\tortts\lib\site-packages\numba\core\errors.py", line 171, in <listcomp>
    if tuple([int(x) for x in colorama_version.split('.')]) < (0, 3, 9):
ValueError: invalid literal for int() with base 10: '5rc1'
```

Did I miss something?

**Comment by neonbjb** [comment]
I haven't a clue, sorry. It looks like some package is trying to parse the string "5rc1" into an integer. You might try using an older version of librosa or numba (and if this works, reporting the issue to them).
