### ISSUE TITLE
Getting following error on windows

### ISSUE THREAD

**Issue by dev-gautam-m** [neonbjb/tortoise-tts#117]
$ python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast
C:\Users\Gautam\AppData\Local\Programs\Python\Python310\lib\site-packages\torchaudio\_internal\module_utils.py:99: UserWarning: Failed to import soundfile. 'soundfile' backend is not available.
  warnings.warn("Failed to import soundfile. 'soundfile' backend is not available.")
Traceback (most recent call last):
  File "C:\Users\Gautam\AppData\Local\Programs\Python\Python310\lib\site-packages\soundfile-0.10.3.post1-py3.10.egg\soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Gautam\Desktop\tortoise-tts\tortoise\do_tts.py", line 7, in <module>
    from api import TextToSpeech, MODELS_DIR
  File "C:\Users\Gautam\Desktop\tortoise-tts\tortoise\api.py", line 22, in <module>
    from tortoise.utils.audio import wav_to_univnet_mel, denormalize_tacotron_mel
  File "C:\Users\Gautam\AppData\Local\Programs\Python\Python310\lib\site-packages\tortoise-2.4.2-py3.10.egg\tortoise\utils\audio.py", line 4, in <module>
    import librosa
  File "C:\Users\Gautam\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa-0.9.1-py3.10.egg\librosa\__init__.py", line 209, in <module>
    from . import core
  File "C:\Users\Gautam\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa-0.9.1-py3.10.egg\librosa\core\__init__.py", line 6, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "C:\Users\Gautam\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa-0.9.1-py3.10.egg\librosa\core\audio.py", line 8, in <module>
    import soundfile as sf
  File "C:\Users\Gautam\AppData\Local\Programs\Python\Python310\lib\site-packages\soundfile-0.10.3.post1-py3.10.egg\soundfile.py", line 162, in <module>
    _snd = _ffi.dlopen(_os.path.join(
OSError: cannot load library 'C:\Users\Gautam\AppData\Local\Programs\Python\Python310\lib\site-packages\soundfile-0.10.3.post1-py3.10.egg\_soundfile_data\libsndfile64bit.dll': error 0x7e

**Comment by neonbjb** [comment]
Hey this is either a problem with librosa or your installation of librosa. I'd try re-installing everything in a new environment following the instructions from the repo. At a bare minimum, you should be able to "import librosa" in a python console.

If it helps, my Windows machine has librosa==0.9.1 on it. That should be a working baseline for you.
