### ISSUE TITLE
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution

### ISSUE THREAD

**Issue by chrisbward** [neonbjb/tortoise-tts#160]
3090 ti, Ubuntu 20.04 - so close!

```
(base) ➜  tortoise-tts git:(main) ✗ python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast
/home/user/.cache/tortoise/models
Generating autoregressive samples..
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:08<00:00,  1.35s/it]
Computing best candidates using CLVP
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:01<00:00,  4.47it/s]
Transforming autoregressive outputs into audio..
Traceback (most recent call last):
  File "/home/user/Projects/04_MachineLearning/tortoise-tts/tortoise/do_tts.py", line 38, in <module>
    gen, dbg_state = tts.tts_with_preset(args.text, k=args.candidates, voice_samples=voice_samples, conditioning_latents=conditioning_latents,
  File "/home/user/Projects/04_MachineLearning/tortoise-tts/tortoise/api.py", line 328, in tts_with_preset
    return self.tts(text, **settings)
  File "/home/user/Projects/04_MachineLearning/tortoise-tts/tortoise/api.py", line 491, in tts
    mel = do_spectrogram_diffusion(self.diffusion, diffuser, latents, diffusion_conditioning,
  File "/home/user/Projects/04_MachineLearning/tortoise-tts/tortoise/api.py", line 155, in do_spectrogram_diffusion
    precomputed_embeddings = diffusion_model.timestep_independent(latents, conditioning_latents, output_seq_len, False)
  File "/home/user/miniconda3/lib/python3.9/site-packages/TorToiSe-2.4.2-py3.9.egg/tortoise/models/diffusion_decoder.py", line 239, in timestep_independent
    code_emb = self.latent_conditioner(aligned_conditioning)
  File "/home/user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 307, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/.local/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 303, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution
```

**Comment by neonbjb** [comment]
I think I've seen this error when I tried to do a convolution on too large of an input. Can you confirm that you trimmed your custom conditioning clip down to less than 30 seconds (ideally 6 seconds) long?

**Comment by chrisbward** [comment]
ok so, I investigated this on nvidia-smi and it was another experiment hanging around that hadn't released the memory, we can close this one - thanks
