### ISSUE TITLE
an error when trying to run the thing

### ISSUE THREAD

**Issue by ethanm22** [neonbjb/tortoise-tts#18]
hello everyone
for some reason, when I run the do_tts python script, I am getting this error: I input my text and select the voice to use, but I still get this: I also have an NVIDIA GPU which I have used to train tacotron models, so I really don't know what is happening here
Traceback (most recent call last):                                                                                        File "C:\Users\thema\Downloads\tortoise-tts-main\do_tts.py", line 22, in <module>                                         tts = TextToSpeech()                                                                                                  File "C:\Users\thema\Downloads\tortoise-tts-main\api.py", line 201, in __init__                                           self.vocoder.load_state_dict(torch.load('.models/vocoder.pth')['model_g'])                                            File "C:\Users\thema\anaconda3\lib\site-packages\torch\serialization.py", line 712, in load                               return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)                                         File "C:\Users\thema\anaconda3\lib\site-packages\torch\serialization.py", line 1046, in _load                             result = unpickler.load()                                                                                             File "C:\Users\thema\anaconda3\lib\site-packages\torch\serialization.py", line 1016, in persistent_load                   load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))                                                        File "C:\Users\thema\anaconda3\lib\site-packages\torch\serialization.py", line 1001, in load_tensor                       wrap_storage=restore_location(storage, location),                                                                     File "C:\Users\thema\anaconda3\lib\site-packages\torch\serialization.py", line 176, in default_restore_location           result = fn(storage, location)                                                                                        File "C:\Users\thema\anaconda3\lib\site-packages\torch\serialization.py", line 152, in _cuda_deserialize                  device = validate_cuda_device(location)                                                                               File "C:\Users\thema\anaconda3\lib\site-packages\torch\serialization.py", line 136, in validate_cuda_device               raise RuntimeError('Attempting to deserialize object on a CUDA '                                                    RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
if anyone could help me with this, I would really appreciate it!

**Comment by neonbjb** [comment]
If you open an interactive python terminal and run torch.cuda.is_available(), what does it say?

**Comment by ethanm22** [comment]
how do I go about doing that? I am not the best at doing this kind of checking stuff

**Comment by neonbjb** [comment]
You just type "python", then  "import torch" then run the command.

**Comment by ethanm22** [comment]
I think I am doing this the rong way: every time I try to do this, it says python: can't open file 'C:\Users\thema\Downloads\import': [Errno 2] No such file or directory

**Comment by ethanm22** [comment]
never mind, figured it out: it says false: I don't know why since I have used it to train AI models before

**Comment by oneandonlyjason** [comment]
Same Error here. It also Says that Cude is not avaible, but other Software can use it. Windows 10 is the Operation System in this Case

**Comment by oneandonlyjason** [comment]
Okay, for me the Problem was that my Cuda Version that i Downloaded from the Nvidia Cuda Website was to new for pytorch. I needed to Install a Nightly Version of Pytorch and Pytorch Audio that supported the Used Cuda Version

**Comment by neonbjb** [comment]
Just an FYI - pytorch typically comes packaged with CUDA. It doesn't matter what you have installed on your system.

That being said, you need to make sure to install a version of Pytorch *with* CUDA, not the CPU only version.

Hopefully you both figured this out. Please re-open if I can help further.
