### ISSUE TITLE
Setting k value above 1 results in RunteimError

### ISSUE THREAD

**Issue by andrewkuo** [neonbjb/tortoise-tts#19]
First off, amazing project! Well done :)

When setting k value above one I get the following runtime error. Tried with values of 2 and 3:

```
Traceback (most recent call last):
  File "C:\KI\Projects\tortoise-tts\api.py", line 228, in tts_with_preset
    return self.tts(text, voice_samples, **kwargs)
  File "C:\KI\Projects\tortoise-tts\api.py", line 343, in tts
    best_latents = self.autoregressive(conds, text, torch.tensor([text.shape[-1]], device=conds.device), best_results,
  File "C:\Users\andre\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\KI\Projects\tortoise-tts\models\autoregressive.py", line 446, in forward
    text_logits, mel_logits = self.get_logits(conds, text_emb, self.text_head, mel_emb, self.mel_head, get_attns=return_attentions, return_latent=return_latent)
  File "C:\KI\Projects\tortoise-tts\models\autoregressive.py", line 368, in get_logits
    emb = torch.cat([speech_conditioning_inputs, first_inputs, second_inputs], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 1 but got size 2 for tensor number 2 in the list.
```

**Comment by neonbjb** [comment]
Will fix in the next merge. Will probably happen tonight.

**Comment by neonbjb** [comment]
(thanks for reporting!)
