### ISSUE TITLE
Trying to install tortoise-tts on a virtual enviroment on linux. I get this error

### ISSUE THREAD

**Issue by gaurav-95** [neonbjb/tortoise-tts#191]
> Traceback (most recent call last):
>   File "/home/ubuntu/neus/cron_radio_tortoise.py", line 26, in <module>
>     tts = TextToSpeech()
>   File "/home/ubuntu/neus/neusenv/lib/python3.10/site-packages/TorToiSe-2.3.0-py3.10.egg/tortoise/api.py", line 184, in __init__
>   File "/home/ubuntu/neus/neusenv/lib/python3.10/site-packages/TorToiSe-2.3.0-py3.10.egg/tortoise/utils/tokenizer.py", line 169, in __init__
> Exception: No such file or directory (os error 2)

'neus' is my work directory and 'neusenv' is the python virtual env. I have cloned the tortoise repo to the 'neus' directory and installed it according to the instructions. I was getting an install error with numba so I removed the version of numba from the requirements file. The installation went through successfully.

The import part of the code is like its mentioned in the colab notebook.

```
# Imports for realistic voices
import torch
import torchaudio
# import torch.nn as nn
# import torch.nn.functional as F
from tortoise.api import TextToSpeech
from tortoise.utils.audio import load_audio, load_voice, load_voices

# This will download all the models used by Tortoise from the HuggingFace hub.
tts = TextToSpeech()
voice = 'train_dotrice'
# Load it and send it through Tortoise.
voice_samples, conditioning_latents = load_voice(voice)
```
Im on ubuntu 22.04 cuda 11.8

When I use it in the virtual environment, I get this error. I tried downgrading to transformers version 4.19 still no luck. 
Please help me out with this.

**Comment by gaurav-95** [comment]
Never mind it works when I clone using this exact repo rather than the one mentioned inside the colab file.

working: git clone https://github.com/neonbjb/tortoise-tts.git
not working: git clone https://github.com/jnordberg/tortoise-tts.git

My bad. Guess I didn't exactly follow instructions. 🤭
