### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by heyitsalicia** [neonbjb/tortoise-tts#26]
after following the instructions EXACTLY as they were written, I get this error:

`C:\Users\no\anaconda3\lib\site-packages\torchaudio\_internal\module_utils.py:99: UserWarning: Failed to import soundfile. 'soundfile' backend is not available.
  warnings.warn("Failed to import soundfile. 'soundfile' backend is not available.")
Traceback (most recent call last):
  File "C:\Users\no\anaconda3\lib\site-packages\soundfile-0.10.3.post1-py3.9.egg\soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\voicecloning\tortoise-tts\tortoise\do_tts.py", line 6, in <module>
    from api import TextToSpeech
  File "d:\voicecloning\tortoise-tts\tortoise\api.py", line 21, in <module>
    from tortoise.utils.audio import wav_to_univnet_mel, denormalize_tacotron_mel
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\no\anaconda3\lib\site-packages\tortoise-2.1.3-py3.9.egg\tortoise\utils\audio.py", line 4, in <module>
  File "C:\Users\no\anaconda3\lib\site-packages\librosa-0.9.1-py3.9.egg\librosa\__init__.py", line 209, in <module>
    from . import core
  File "C:\Users\no\anaconda3\lib\site-packages\librosa-0.9.1-py3.9.egg\librosa\core\__init__.py", line 6, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "C:\Users\no\anaconda3\lib\site-packages\librosa-0.9.1-py3.9.egg\librosa\core\audio.py", line 8, in <module>
    import soundfile as sf
  File "C:\Users\no\anaconda3\lib\site-packages\soundfile-0.10.3.post1-py3.9.egg\soundfile.py", line 162, in <module>
    _snd = _ffi.dlopen(_os.path.join(
OSError: cannot load library 'C:\Users\no\anaconda3\lib\site-packages\soundfile-0.10.3.post1-py3.9.egg\_soundfile_data\libsndfile64bit.dll': error 0x7e`

so, i figured "why don't i just install soundfile since it doesn't exist?"

(base) d:\voicecloning\tortoise-tts>pip install soundfile
Requirement already satisfied: soundfile in c:\users\no\anaconda3\lib\site-packages\soundfile-0.10.3.post1-py3.9.egg (0.10.3.post1)
Requirement already satisfied: cffi>=1.0 in c:\users\no\anaconda3\lib\site-packages (from soundfile) (1.14.6)
Requirement already satisfied: pycparser in c:\users\no\anaconda3\lib\site-packages (from cffi>=1.0->soundfile) (2.20)

oh so now it's going to tell me that it already exists but then says it doesn't when i run it.

so, what gives. why doesn't this work?

**Comment by neonbjb** [comment]
Not sure, but this is a a package management issue of some sort and doesn't have anything to do with Tortoise. I'd start fresh from a new conda environment and try again: 
```
conda create --name tortoise
conda activate tortoise
<repeat torch installation>
<repeat tortoise installation instructions>
```

If you want to keep your base env, I'd recommend purging any soundfile packages you have installed and re-installing them. Try from both pip, then conda (purging between): https://stackoverflow.com/questions/62543843/cannot-import-torch-audio-no-audio-backend-is-available

**Comment by heyitsalicia** [comment]
that is strange, I thought I had gone into the environment I had created before, until now I didn't notice I was still in the base environment, I will try again
