### ISSUE TITLE
ValueError: zero-size array message while using microphone for audio

### ISSUE THREAD

**Issue by ProgrammingBlob** [neonbjb/tortoise-tts#289]
It seems to be an issue only when recording audio directly from the browser. I assumed that it could be related to the device that I'm recording from, but specific issues caught my eye. I'm able to produce results using the text box normally. But no settings I've adjusted from while using a pre-recorded voice for output has given a stable result. 

```
C:\Users\B\anaconda3\lib\site-packages\gradio\processing_utils.py:241: **UserWarning: Trying to convert audio automatically from int32 to 16-bit int format.**
  warnings.warn(warning.format(data.dtype))
Generating autoregressive samples
Computing best candidates using CLVP
Transforming autoregressive outputs into audio..
C:\Users\B\anaconda3\lib\site-packages\gradio\processing_utils.py:236: UserWarning: **Trying to convert audio automatically from float32 to 16-bit int format.**
  warnings.warn(warning.format(data.dtype))
Traceback (most recent call last):
  File "C:\Users\B\anaconda3\lib\site-packages\gradio\routes.py", line 344, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\B\anaconda3\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\B\anaconda3\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\B\anaconda3\lib\site-packages\gradio\components.py", line 2154, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\Users\B\anaconda3\lib\site-packages\gradio\processing_utils.py", line 221, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\Users\B\anaconda3\lib\site-packages\gradio\processing_utils.py", line 237, in convert_to_16_bit_wav
    data = data / np.abs(data).max()
  File "C:\Users\B\anaconda3\lib\site-packages\numpy\core\_methods.py", line 40, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
**ValueError: zero-size array to reduction operation maximum which has no identity**
```

**Comment by neonbjb** [comment]
I don't know exactly what this problem is, but I'd bet a lot of money that `result['prediction']` is not the right tensor shape or dtype that gradio expects. Looks like it wants 16 bit ints. There's probably some good tutorials out there on how to get the formatting right.
