### ISSUE TITLE
python setup.py bdist_wheel did not run successfully.

### ISSUE THREAD

**Issue by vipankumar87** [neonbjb/tortoise-tts#305]
getting error at 

 pip install -r requirements.txt

      copying numba/cuda/tests/cudapy/test_idiv.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_cuda_autojit.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_record_dtype.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_vectorize_decor.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_vectorize_device.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_gufunc_scalar.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_sm.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_ipc.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_vectorize_scalar_arg.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_forall.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_array_args.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_debuginfo.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_exception.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_transpose.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_atomics.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_device_func.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_boolean.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_deprecation.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_retrieve_autoconverted_arrays.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_array.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_cuda_array_interface.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_random.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_userexc.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_complex_kernel.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_py2_div_issue.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_operator.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_const_string.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_debug.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_serialize.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_alignment.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_print.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_intrinsics.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_gufunc_scheduling.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_vectorize.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_laplace.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_localmem.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_globals.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      copying numba/cuda/tests/cudapy/test_multithreads.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudapy
      creating build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudadrv/data
      copying numba/cuda/tests/cudadrv/data/__init__.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudadrv/data
      creating build/lib.linux-x86_64-cpython-310/numba/cuda/simulator/cudadrv
      copying numba/cuda/simulator/cudadrv/devices.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/simulator/cudadrv
      copying numba/cuda/simulator/cudadrv/devicearray.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/simulator/cudadrv
      copying numba/cuda/simulator/cudadrv/__init__.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/simulator/cudadrv
      copying numba/cuda/simulator/cudadrv/nvvm.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/simulator/cudadrv
      copying numba/cuda/simulator/cudadrv/driver.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/simulator/cudadrv
      copying numba/cuda/simulator/cudadrv/drvapi.py -> build/lib.linux-x86_64-cpython-310/numba/cuda/simulator/cudadrv
      creating build/lib.linux-x86_64-cpython-310/numba/roc/tests
      copying numba/roc/tests/__init__.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests
      creating build/lib.linux-x86_64-cpython-310/numba/roc/hsadrv
      copying numba/roc/hsadrv/devices.py -> build/lib.linux-x86_64-cpython-310/numba/roc/hsadrv
      copying numba/roc/hsadrv/devicearray.py -> build/lib.linux-x86_64-cpython-310/numba/roc/hsadrv
      copying numba/roc/hsadrv/enums_ext.py -> build/lib.linux-x86_64-cpython-310/numba/roc/hsadrv
      copying numba/roc/hsadrv/__init__.py -> build/lib.linux-x86_64-cpython-310/numba/roc/hsadrv
      copying numba/roc/hsadrv/driver.py -> build/lib.linux-x86_64-cpython-310/numba/roc/hsadrv
      copying numba/roc/hsadrv/drvapi.py -> build/lib.linux-x86_64-cpython-310/numba/roc/hsadrv
      copying numba/roc/hsadrv/enums.py -> build/lib.linux-x86_64-cpython-310/numba/roc/hsadrv
      copying numba/roc/hsadrv/error.py -> build/lib.linux-x86_64-cpython-310/numba/roc/hsadrv
      creating build/lib.linux-x86_64-cpython-310/numba/roc/hlc
      copying numba/roc/hlc/libhlc.py -> build/lib.linux-x86_64-cpython-310/numba/roc/hlc
      copying numba/roc/hlc/config.py -> build/lib.linux-x86_64-cpython-310/numba/roc/hlc
      copying numba/roc/hlc/__init__.py -> build/lib.linux-x86_64-cpython-310/numba/roc/hlc
      copying numba/roc/hlc/common.py -> build/lib.linux-x86_64-cpython-310/numba/roc/hlc
      copying numba/roc/hlc/hlc.py -> build/lib.linux-x86_64-cpython-310/numba/roc/hlc
      creating build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsadrv
      copying numba/roc/tests/hsadrv/__init__.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsadrv
      copying numba/roc/tests/hsadrv/test_driver.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsadrv
      copying numba/roc/tests/hsadrv/test_async.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsadrv
      creating build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/test_reduction.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/test_math.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/test_autojit.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/test_matmul.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/test_simple.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/test_positioning.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/test_memory.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/__init__.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/test_linkage.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/test_occupancy.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/test_ufuncbuilding.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/test_scan.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/test_large_code.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/test_atomics.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/test_async_kernel.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/test_compiler.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/run_far_branch.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/test_decorator.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/test_barrier.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/test_intrinsics.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/roc/tests/hsapy/test_gufuncbuilding.py -> build/lib.linux-x86_64-cpython-310/numba/roc/tests/hsapy
      copying numba/_lapack.c -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/_dynfuncmod.c -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/_hashtable.c -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/_random.c -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/_npymath_exports.c -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/_math_c99.c -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/_helpermod.c -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/_helperlib.c -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/mviewbuf.c -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/_typeof.c -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/_dynfunc.c -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/_dispatcher.c -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/_numba_common.h -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/_dispatcher.h -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/_math_c99.h -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/_unicodetype_db.h -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/_typeof.h -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/capsulethunk.h -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/_hashtable.h -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/_pymodule.h -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/mathnames.h -> build/lib.linux-x86_64-cpython-310/numba
      copying numba/_arraystruct.h -> build/lib.linux-x86_64-cpython-310/numba
      creating build/lib.linux-x86_64-cpython-310/numba/tests/pycc_distutils_usecase
      copying numba/tests/pycc_distutils_usecase/setup_distutils.py -> build/lib.linux-x86_64-cpython-310/numba/tests/pycc_distutils_usecase
      copying numba/tests/pycc_distutils_usecase/source_module.py -> build/lib.linux-x86_64-cpython-310/numba/tests/pycc_distutils_usecase
      copying numba/tests/pycc_distutils_usecase/setup_setuptools.py -> build/lib.linux-x86_64-cpython-310/numba/tests/pycc_distutils_usecase
      copying numba/runtime/_nrt_pythonmod.c -> build/lib.linux-x86_64-cpython-310/numba/runtime
      copying numba/runtime/nrt.c -> build/lib.linux-x86_64-cpython-310/numba/runtime
      copying numba/runtime/_nrt_python.c -> build/lib.linux-x86_64-cpython-310/numba/runtime
      copying numba/runtime/nrt_external.h -> build/lib.linux-x86_64-cpython-310/numba/runtime
      copying numba/runtime/nrt.h -> build/lib.linux-x86_64-cpython-310/numba/runtime
      copying numba/annotations/template.html -> build/lib.linux-x86_64-cpython-310/numba/annotations
      copying numba/pycc/modulemixin.c -> build/lib.linux-x86_64-cpython-310/numba/pycc
      copying numba/cext/listobject.c -> build/lib.linux-x86_64-cpython-310/numba/cext
      copying numba/cext/dictobject.c -> build/lib.linux-x86_64-cpython-310/numba/cext
      copying numba/cext/utils.c -> build/lib.linux-x86_64-cpython-310/numba/cext
      copying numba/cext/cext.h -> build/lib.linux-x86_64-cpython-310/numba/cext
      copying numba/cext/listobject.h -> build/lib.linux-x86_64-cpython-310/numba/cext
      copying numba/cext/dictobject.h -> build/lib.linux-x86_64-cpython-310/numba/cext
      copying numba/targets/cmdlang.gdb -> build/lib.linux-x86_64-cpython-310/numba/targets
      copying numba/cuda/tests/cudadrv/data/jitlink.ptx -> build/lib.linux-x86_64-cpython-310/numba/cuda/tests/cudadrv/data
      running build_ext
      building 'numba._dynfunc' extension
      Warning: Can't read registry to find the necessary compiler setting
      Make sure that Python modules winreg, win32api or win32con are installed.
      INFO: C compiler: gcc -pthread -B /home/striker/miniconda3/envs/tortoise-tts/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/striker/miniconda3/envs/tortoise-tts/include -fPIC -O2 -isystem /home/striker/miniconda3/envs/tortoise-tts/include -fPIC
      
      creating build/temp.linux-x86_64-cpython-310
      creating build/temp.linux-x86_64-cpython-310/numba
      INFO: compile options: '-I/home/striker/miniconda3/envs/tortoise-tts/include/python3.10 -c'
      extra options: '-g'
      INFO: gcc: numba/_dynfuncmod.c
      INFO: gcc -pthread -B /home/striker/miniconda3/envs/tortoise-tts/compiler_compat -shared -Wl,-rpath,/home/striker/miniconda3/envs/tortoise-tts/lib -Wl,-rpath-link,/home/striker/miniconda3/envs/tortoise-tts/lib -L/home/striker/miniconda3/envs/tortoise-tts/lib -Wl,-rpath,/home/striker/miniconda3/envs/tortoise-tts/lib -Wl,-rpath-link,/home/striker/miniconda3/envs/tortoise-tts/lib -L/home/striker/miniconda3/envs/tortoise-tts/lib build/temp.linux-x86_64-cpython-310/numba/_dynfuncmod.o -o build/lib.linux-x86_64-cpython-310/numba/_dynfunc.cpython-310-x86_64-linux-gnu.so
      building 'numba._dispatcher' extension
      INFO: C compiler: gcc -pthread -B /home/striker/miniconda3/envs/tortoise-tts/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/striker/miniconda3/envs/tortoise-tts/include -fPIC -O2 -isystem /home/striker/miniconda3/envs/tortoise-tts/include -fPIC
      
      creating build/temp.linux-x86_64-cpython-310/numba/typeconv
      INFO: compile options: '-I/home/striker/miniconda3/envs/tortoise-tts/lib/python3.10/site-packages/numpy/core/include -I/home/striker/miniconda3/envs/tortoise-tts/include/python3.10 -c'
      INFO: gcc: numba/_dispatcher.c
      INFO: gcc: numba/_dispatcherimpl.cpp
      INFO: gcc: numba/_hashtable.c
      INFO: gcc: numba/_typeof.c
      INFO: gcc: numba/typeconv/typeconv.cpp
      numba/_dispatcher.c: In function ‘call_trace’:
      numba/_dispatcher.c:26:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘use_tracing’; did you mean ‘tracing’?
         26 |     tstate->use_tracing = 0;
            |             ^~~~~~~~~~~
            |             tracing
      numba/_dispatcher.c:28:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘use_tracing’; did you mean ‘tracing’?
         28 |     tstate->use_tracing = ((tstate->c_tracefunc != NULL)
            |             ^~~~~~~~~~~
            |             tracing
      numba/_dispatcher.c: In function ‘call_cfunc’:
      numba/_dispatcher.c:301:17: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘use_tracing’; did you mean ‘tracing’?
        301 |     if (tstate->use_tracing && tstate->c_profilefunc)
            |                 ^~~~~~~~~~~
            |                 tracing
      numba/_dispatcher.c: In function ‘Dispatcher_call’:
      numba/_dispatcher.c:507:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘use_tracing’; did you mean ‘tracing’?
        507 |     if (ts->use_tracing && ts->c_profilefunc)
            |             ^~~~~~~~~~~
            |             tracing
      numba/_dispatcher.c: In function ‘call_cfunc’:
      numba/_dispatcher.c:349:1: warning: control reaches end of non-void function [-Wreturn-type]
        349 | }
            | ^
      error: Command "gcc -pthread -B /home/striker/miniconda3/envs/tortoise-tts/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/striker/miniconda3/envs/tortoise-tts/include -fPIC -O2 -isystem /home/striker/miniconda3/envs/tortoise-tts/include -fPIC -I/home/striker/miniconda3/envs/tortoise-tts/lib/python3.10/site-packages/numpy/core/include -I/home/striker/miniconda3/envs/tortoise-tts/include/python3.10 -c numba/_dispatcher.c -o build/temp.linux-x86_64-cpython-310/numba/_dispatcher.o" failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  Building wheel for llvmlite (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      /home/striker/miniconda3/envs/tortoise-tts/bin/python /tmp/pip-install-zbdj0xw9/llvmlite_baca219dc6cb4f59ac8711f9ffec344d/ffi/build.py
      LLVM version... 11.1.0
      
      Traceback (most recent call last):
        File "/tmp/pip-install-zbdj0xw9/llvmlite_baca219dc6cb4f59ac8711f9ffec344d/ffi/build.py", line 168, in <module>
          main()
        File "/tmp/pip-install-zbdj0xw9/llvmlite_baca219dc6cb4f59ac8711f9ffec344d/ffi/build.py", line 158, in main
          main_posix('linux', '.so')
        File "/tmp/pip-install-zbdj0xw9/llvmlite_baca219dc6cb4f59ac8711f9ffec344d/ffi/build.py", line 120, in main_posix
          raise RuntimeError(msg)
      RuntimeError: Building llvmlite requires LLVM 7.0+ Be sure to set LLVM_CONFIG to the right executable path.
      Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
      
      error: command '/home/striker/miniconda3/envs/tortoise-tts/bin/python' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build numpy numba llvmlite
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects

**Comment by frosta95** [comment]
I have sadly the same problem as you right now....

**Comment by neonbjb** [comment]
Sorry, haven't got a clue. I'd try to get a python environment set up that can fun basic pytorch programs that use the gpu. There are lots of troubleshooting guides out there for that. Once you have that set up, getting tortoise going in that environment should be trivial.

**Comment by sbersier** [comment]
Could you try the following:
1) make a copy of requirements.txt as resquirments.txt.OLD and save it. Sp that you can always go go back to the origin.
2) Edit the requirements.txt file as following:
- remove the version requirement of numpy
- remove the version requirement on numba
That is, you replace:
```
numpy==1.20.0
numba==0.48.0
```

with:
```
numpy
numba
```

Does it work?

**Comment by vipankumar87** [comment]
yes, it is worked

**Comment by TemmieYT** [comment]
wait where do i find requirements.txt?

**Comment by sbersier** [comment]
The manipulation described above is not necessary anymore since the requirements for specific versions of numpy and numba were removed.

If you have problems installing it I would suggest the following:

1) uninstall/remove your previous attempt(s)

2) In a terminal:
```
git clone https://github.com/neonbjb/tortoise-tts.git
cd tortoise-tts
```
3) Create a python virtual environnement.
`python3 -m venv tortoise`
and activate it:
`source tortoise/bin/activate`
(You'll have to activate it everytime).

4) Now, the difficult part... Installing torch, torchaudio and torchvision
The simplest way of installing torch is by not installing it yourself but let pip figure out which torch version will fit your needs.
So, I would recommend first installing torchvision. Pip will search for a torch version that will fit. (Note: torchaudio is included in the requirements.txt) 

```
pip install torchvision
```

5) Install the rest of requirements:
`pip install -r requirements.txt`

6) Install tortoise:
`python setup.py  install`

7) Test:
`python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast`
You should find 3 results in the results folder.

8) When you're finished, you can deactivate the virtual environnment with:
`deactivate`
