### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by xiaoqin00** [neonbjb/tortoise-tts#32]
oh，no
i meet error this morning.

Traceback (most recent call last):
File "tortoise/do_tts.py", line 27, in
tts = TextToSpeech(models_dir=args.model_dir)
File "C:\plan\test3\tortoise-tts-main\tortoise\api.py", line 196, in init
self.autoregressive.load_state_dict(torch.load(f'{models_dir}/autoregressive.pth'))
File "C:\plan\test3\venv\lib\site-packages\torch\serialization.py", line 713, in load
return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
File "C:\plan\test3\venv\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

![image](https://user-images.githubusercontent.com/13318706/167235630-0dbd828f-eb51-468e-ae30-c36da0505956.png)

**Comment by xiaoqin00** [comment]
maybe because this

![image](https://user-images.githubusercontent.com/13318706/167235952-f94e71ef-08f3-4426-b957-66203cc3d4e0.png)
