### ISSUE TITLE
SSL Certification problem

### ISSUE THREAD

**Issue by hobik** [neonbjb/tortoise-tts#321]
When I try to use basic test commands I get below error:
```
 python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast

Downloading autoregressive.pth from https://huggingface.co/jbetker/tortoise-tts-v2/resolve/main/.models/autoregressive.pth...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/duygu/tortoise-tts/tortoise/do_tts.py", line 27, in <module>
    tts = TextToSpeech(models_dir=args.model_dir)
  File "/Users/duygu/tortoise-tts/tortoise/api.py", line 231, in __init__
    self.autoregressive.load_state_dict(torch.load(get_model_path('autoregressive.pth', models_dir)))
  File "/Users/duygu/tortoise-tts/tortoise/api.py", line 79, in get_model_path
    download_models([model_name])
  File "/Users/duygu/tortoise-tts/tortoise/api.py", line 67, in download_models
    request.urlretrieve(url, model_path, show_progress)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>

```
How can I solve this problem ?

**Comment by thesandwichman294** [comment]
I had the same issue to get it working you need to manually download the models and add them to ~/.cache/tortoise/models

These are the files needed
https://huggingface.co/jbetker/tortoise-tts-v2/resolve/main/.models/autoregressive.pth
https://huggingface.co/jbetker/tortoise-tts-v2/resolve/main/.models/classifier.pth
https://huggingface.co/jbetker/tortoise-tts-v2/resolve/main/.models/clvp2.pth
https://huggingface.co/jbetker/tortoise-tts-v2/resolve/main/.models/cvvp.pth
https://huggingface.co/jbetker/tortoise-tts-v2/resolve/main/.models/diffusion_decoder.pth
https://huggingface.co/jbetker/tortoise-tts-v2/resolve/main/.models/vocoder.pth
https://huggingface.co/jbetker/tortoise-tts-v2/resolve/main/.models/rlg_auto.pth
https://huggingface.co/jbetker/tortoise-tts-v2/resolve/main/.models/rlg_diffuser.pth'

The models are listed in tortoise-tts/tortoise/api.py but not sure what the proper fix would be since I don't know python.

To make it faster I used [aria2c](https://aria2.github.io/) to batch download the files and save them to to the correct directory but you could use curl/wget or anything that downloads files
```
aria2c -s16 -x16 -d ~/ -o .cache/tortoise/models/autoregressive.pth https://huggingface.co/jbetker/tortoise-tts-v2/resolve/main/.models/autoregressive.pth
aria2c -s16 -x16 -d ~/ -o .cache/tortoise/models/classifier.pth https://huggingface.co/jbetker/tortoise-tts-v2/resolve/main/.models/classifier.pth
aria2c -s16 -x16 -d ~/ -o .cache/tortoise/models/clvp2.pth https://huggingface.co/jbetker/tortoise-tts-v2/resolve/main/.models/clvp2.pth
aria2c -s16 -x16 -d ~/ -o .cache/tortoise/models/cvvp.pth https://huggingface.co/jbetker/tortoise-tts-v2/resolve/main/.models/cvvp.pth
aria2c -s16 -x16 -d ~/ -o .cache/tortoise/models/diffusion_decoder.pth https://huggingface.co/jbetker/tortoise-tts-v2/resolve/main/.models/diffusion_decoder.pth
aria2c -s16 -x16 -d ~/ -o .cache/tortoise/models/vocoder.pth https://huggingface.co/jbetker/tortoise-tts-v2/resolve/main/.models/vocoder.pth
aria2c -s16 -x16 -d ~/ -o .cache/tortoise/models/rlg_auto.pth https://huggingface.co/jbetker/tortoise-tts-v2/resolve/main/.models/rlg_auto.pth
aria2c -s16 -x16 -d ~/ -o .cache/tortoise/models/rlg_diffuser.pth https://huggingface.co/jbetker/tortoise-tts-v2/resolve/main/.models/rlg_diffuser.pth
```
