### ISSUE TITLE
Tortoise TTS on Arch Linux

### ISSUE THREAD

**Issue by DaveJarvis** [neonbjb/tortoise-tts#341]
# Description

Using Arch Linux and pip3.10 to install Tortoise TTS. The tortoise module cannot be found. Here are the instructions I followed:

``` bash
python -m ensurepip
export PATH="$PATH:$HOME/.local/bin"
cd /tmp
git clone https://github.com/neonbjb/tortoise-tts.git
cd tortoise-tts/
sed -i 's/numpy.*/numpy/g' requirements.txt
sed -i 's/numba.*/numba/g' requirements.txt
python -m pip install -r ./requirements.txt
python setup.py install --root $HOME/.local/bin/tortoise-tts
python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast
```

# Expected

Audio file produced.

# Actual

```
Traceback (most recent call last):
  File "/tmp/tortoise-tts/tortoise/do_tts.py", line 7, in <module>
    from api import TextToSpeech, MODELS_DIR
  File "/tmp/tortoise-tts/tortoise/api.py", line 12, in <module>
    from tortoise.models.classifier import AudioMiniEncoderWithClassifierHead
ModuleNotFoundError: No module named 'tortoise'
```

# Question

Any idea why the module cannot be found?

# System

```
$ python --version
Python 3.10.9
$ nvidia-smi --query-gpu=gpu_name --format=csv,noheader --id=0 | sed -e 's/ /-/g'
NVIDIA-T1000-8GB
```

**Comment by DaveJarvis** [comment]
* Removed pip
* Re-installed pip using python-pip package
* Switched to [mrq](https://git.ecker.tech/mrq/tortoise-tts)
