### ISSUE TITLE
tortoise-2.3.0-py3.10.egg

### ISSUE THREAD

**Issue by hawaricracker** [neonbjb/tortoise-tts#348]
Traceback (most recent call last):
  File "D:\copy\voice.py", line 15, in <module>
    tts = TextToSpeech()
  File "D:\New folder (2)\lib\site-packages\tortoise-2.3.0-py3.10.egg\tortoise\api.py", line 184, in __init__
  File "D:\New folder (2)\lib\site-packages\tortoise-2.3.0-py3.10.egg\tortoise\utils\tokenizer.py", line 169, in __init__
Exception: The system cannot find the path specified. (os error 3)

How i can fix this?

**Comment by neonbjb** [comment]
You didn't get one of the data files needed to initialize the tokenizer. I don't know what the solution is.
