### ISSUE TITLE
autoregressive.pth error

### ISSUE THREAD

**Issue by hawaricracker** [neonbjb/tortoise-tts#350]
Traceback (most recent call last):
  File "D:\copy\voice.py", line 15, in <module>
    tts = TextToSpeech()
  File "D:\New folder (2)\lib\site-packages\tortoise-2.4.2-py3.10.egg\tortoise\api.py", line 231, in __init__
    self.autoregressive.load_state_dict(torch.load(get_model_path('autoregressive.pth', models_dir)))
  File "D:\New folder (2)\lib\site-packages\torch\serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "D:\New folder (2)\lib\site-packages\torch\serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

previously I ran this program and it started downloading autoregressive.pth but I immediately stopped the program, then when I run it again the above error appears. do i have to download the autoregressive file manually and put it in the models folder?

**Comment by hawaricracker** [comment]
I have found a solution, namely by deleting the tortoise folder in /home/username/.cache and then rerun the program

**Comment by snehangsude** [comment]
@hawaricracker looking into the `/home` shows the folder as empty - how are you locating the `.cache` file?

**Comment by hawaricracker** [comment]
> @hawaricracker looking into the `/home` shows the folder as empty - how are you locating the `.cache` file?

that's a hidden file

**Comment by snehangsude** [comment]
Ah! Thanks. I was on Ubuntu.

> This issue can be replicated though in Google Colab and Ubuntu.

**Comment by weasam** [comment]
> I have found a solution, namely by deleting the tortoise folder in /home/username/.cache and then rerun the program
This work for me, appreciated 
C:\Users\[username]\.cache\
del huggingface
del tortoise

**Comment by hevldawn** [comment]
it worked for me, thanks
