### ISSUE TITLE
Windows Installation Fails 'ValueError: 'build\\py3k\\scipy' is not a directory'

### ISSUE THREAD

**Issue by Mozoloa** [neonbjb/tortoise-tts#367]
Here's what I did in my AI folder

```
conda init powershell
conda create -n tortoise
conda activate tortoise
(tortoise) git clone https://github.com/neonbjb/tortoise-tts.git
(tortoise) cd tortoise-tts
(tortoise) python -m pip install -r ./requirements.txt
```

First I get a warning saying:
```
 Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1002 lines of output]
      C:\Users\Emperor\AppData\Local\Temp\pip-install-jsa7p9o6\scipy_8f08a00b90024c30bea8e20c66488ca0\setup.py:147: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
```

Then at the end I get 

```
 C:\Users\Emperor\AppData\Local\Temp\pip-install-jsa7p9o6\scipy_8f08a00b90024c30bea8e20c66488ca0\build\py3k\scipy\stats\stats.py
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Emperor\AppData\Local\Temp\pip-install-jsa7p9o6\scipy_8f08a00b90024c30bea8e20c66488ca0\setup.py", line 196, in <module>
          setup_package()
        File "C:\Users\Emperor\AppData\Local\Temp\pip-install-jsa7p9o6\scipy_8f08a00b90024c30bea8e20c66488ca0\setup.py", line 176, in setup_package
          setup(
        File "C:\Users\Emperor\miniconda3\lib\site-packages\numpy\distutils\core.py", line 135, in setup
          config = configuration()
        File "C:\Users\Emperor\AppData\Local\Temp\pip-install-jsa7p9o6\scipy_8f08a00b90024c30bea8e20c66488ca0\setup.py", line 138, in configuration
          config.add_subpackage('scipy')
        File "C:\Users\Emperor\miniconda3\lib\site-packages\numpy\distutils\misc_util.py", line 1050, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
        File "C:\Users\Emperor\miniconda3\lib\site-packages\numpy\distutils\misc_util.py", line 1016, in get_subpackage
          config = self._get_configuration_from_setup_py(
        File "C:\Users\Emperor\miniconda3\lib\site-packages\numpy\distutils\misc_util.py", line 958, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "C:\Users\Emperor\AppData\Local\Temp\pip-install-jsa7p9o6\scipy_8f08a00b90024c30bea8e20c66488ca0\build\py3k\scipy\setup.py", line 4, in configuration
          config = Configuration('scipy',parent_package,top_path)
        File "C:\Users\Emperor\miniconda3\lib\site-packages\numpy\distutils\misc_util.py", line 807, in __init__
          raise ValueError("%r is not a directory" % (package_path,))
      ValueError: 'build\\py3k\\scipy' is not a directory
      [end of output]
```

My Env python:
`Python 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)] on win32`

**Comment by AvaCadava** [comment]
Same here.

**Comment by Mozoloa** [comment]
I ended up using this repo which seems way more advanced : https://github.com/152334H/tortoise-tts-fast/issues

**Comment by gsgoldma** [comment]
same

**Comment by gibsonfan2332** [comment]
same

**Comment by gsgoldma** [comment]
> I ended up using this repo which seems way more advanced : https://github.com/152334H/tortoise-tts-fast/issues

wow way better. nice interface, and went from 30 minutes for a single sentence to about 3-5 minutes

**Comment by rkotowicz** [comment]
I have same error, thinking it's this issue in scipy version #374
