### ISSUE TITLE
Unable to create new voice profile.

### ISSUE THREAD

**Issue by OutcastsAnonymous** [neonbjb/tortoise-tts#369]
So, I've been able to get Tortoise up and running on my PC, and I am able to have it generate correctly for any of the provided voices that come with the software. Even after following the on-page instructions however, I can't get the program to recognize the custom voice profile I have set up.

I've created the folder, and named it in all lower-case just like the rest, and placed it into the voice's folder along side the default ones. I have also filled the folder with appropriately cut up bits of dialogue for it to use. However in a repeatable event, trying to get the program to actually use those voice-lines- or even recognize the folder, ends with the following error message; name redacted:

-------------------------------

(base) C:\Users\MYNAME\tortoise-tts>python tortoise/do_tts.py --text "Please, at this point I will sacrifice a goat to you, if it means getting you to work." --voice cortana --preset fast --output_path C:\Users\MYNAME\Downloads
Traceback (most recent call last):
  File "C:\Users\MYNAME\tortoise-tts\tortoise\do_tts.py", line 35, in <module>
    voice_samples, conditioning_latents = load_voices(voice_sel)
  File "C:\Users\MYNAME\tortoise-tts\tortoise\utils\audio.py", line 124, in load_voices
    clip, latent = load_voice(voice, extra_voice_dirs)
  File "C:\Users\MYNAME\tortoise-tts\tortoise\utils\audio.py", line 105, in load_voice
    paths = voices[voice]
KeyError: 'cortana'

------------------------------

I would also like to make it clear that I have only gotten the program to work through extensive reading of the instructions- and tutorial videos, as I am in no way able to code. I barely understand how these things work, so if I'm just forgetting to run a specific command first then I would not be surprised- but since by all I know of, this should not be happening, I'm for now going to report it as a bug.

My apologies if it's not, and I hope you have a good day <3

**Comment by raff7** [comment]
I'm experiencing the exact same issue

**Comment by raff7** [comment]
i found a solution

Basically it doesn't find the files in the repository folder itself, but rather in the installed package, so if you first do the setup.py step, and then create a new folder, it will not be able to see it.. just run setup.py again and your folder will now work

**Comment by MushFunGus** [comment]
**I did find a fix that worked for me at the bottom final paragraph, I recommend just reading that and see if it applies to you**

For the most part it is exactly the same issue for me, I ran a test using some of the train_ voices and it runs perfectly, just seems to be a problem with custom voices. The reinstall method didn't make a difference in my case.

First thing to check is that the files are formatted correctly as floating point. (Mine are not but I'll update on the output at the end)

What I'll try first instead is to move the audio files to the established folder that DID work and see if it can suddenly read it, that would at least prove the validity of raff7's fix, just means that reinstalling didn't remedy that on my part.

I did also attempt to append '--extra-voice-dirs /path/to/custom_voices' but it was seen as invalid.

----
I ran my original dialogue with kennard and it went perfectly as expected.
I backed up the 2 files from kennard and replaced the audio with 10 or so clips from my custom dataset.
I ran it again and so far it has managed to start compiling the audio contrary to using a custom folder.
It compiled however still used the original voice, oddly enough, could it be pulling the voices not from within the lib/tortoise/voices folder?
----

**My Fix**
From this I have discovered a secondary voice folder. The mistake may well have been because I was putting the voices in the **tortoise-tts/build/lib/tortoise/voices folder** when it in fact should be in the **tortoise-tts/tortoise/voices** folder, somehow this went entirely over my head, but with that, when placing the custom folder inside, it now registers and compiles.

Feels like a really dumb mistake on my end but it's nice to have it sorted and hopefully this can save a little hair pulling if it afflicted anyone else.

**Comment by G-force78** [comment]
Made no difference to me I have the right folder paths yet it still errors with load voice not defined. Driving me nuts

**Comment by hevldawn** [comment]
got the same issue, very frustratring

**Comment by yatesdr** [comment]
I had this issue too, but was able to solve it by putting the clips in ./tortoise/voices/snoop and then running python3 setup.py install.   It found the voice and let me use it, anyway.   It sounds nothing like snoop though, so I guess it needs to be fine tuned to have a shot at working well enough to bother with.

Another issue I had was installing scipy, I think there's an error in the requirements.txt where it's asking for 0.10.1 and needs something much newer.   0.10.1 runs on python2.   I removed all the requirement freezes and it loaded fine in a fresh venv though.

**Comment by Aqirito** [comment]
I also got this error. But I use API in my scripts. I saw that the audio.py is running inside site-package of my virtual environment. ```\venv\Lib\site-packages\TorToiSe-2.4.2-py3.8.egg\tortoise\utils```.
What I do is completely change the entire project make it on my own use.

1. delete .git file. this will remove the git completely.
2. rename the "tortoise-tts" to "tortoiseTTS" for easy import later.
3. change the orginal import:
```
from tortoise.api import TextToSpeech
from tortoise.utils.audio import load_audio, load_voice, load_voices
```
to
```
from tortoiseTTS.tortoise.api import TextToSpeech
from tortoiseTTS.tortoise.utils.audio import load_audio, load_voice, load_voices
```

**Comment by kostianu4** [comment]
well, I also found solution, somehow I have tortoise inside another tortoise folder, so my workind dir is:
C:\Users\{UserName}\tortoise-tts\tortoise-tts\tortoise\voices

**Comment by amit-parmar** [comment]
@Aqirito Thank you, your solution is worked and this is how it should be done.
