### ISSUE TITLE
GPU Out of Memory

### ISSUE THREAD

**Issue by kdrkdrkdr** [neonbjb/tortoise-tts#37]
I'm a user using a 4GB GPU. Can this be resolved using 'torch.cuda.empty_cache()'? If not, can I get a solution?

Error Message

> python tortoise/do_tts.py --text "I'm going to speak this" --voice lj --preset fast

Generating autoregressive samples..
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:11<00:00,  1.96s/it]
Computing best candidates using CLVP and CVVP
  0%|                                                                                                          | 0/6 [00:00<?, ?it/s]C:\Anaconda3\envs\laver\lib\site-packages\torch\utils\checkpoint.py:25: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
  0%|                                                                                                          | 0/6 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "tortoise/do_tts.py", line 29, in <module>
    gen = tts.tts_with_preset(args.text, voice_samples=voice_samples, conditioning_latents=conditioning_latents,
  File "C:\Users\power\Desktop\Project\Dev\tortoise-tts\tortoise\api.py", line 288, in tts_with_preset
    return self.tts(text, **kwargs)
  File "C:\Users\power\Desktop\Project\Dev\tortoise-tts\tortoise\api.py", line 392, in tts
    clvp = self.clvp(text_tokens.repeat(batch.shape[0], 1), batch, return_loss=False)
  File "C:\Anaconda3\envs\laver\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Anaconda3\envs\laver\lib\site-packages\torch\utils\checkpoint.py", line 235, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "C:\Anaconda3\envs\laver\lib\site-packages\torch\utils\checkpoint.py", line 96, in forward
    outputs = run_function(*args)
  File "C:\Anaconda3\envs\laver\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Anaconda3\envs\laver\lib\site-packages\tortoise-2.2.0-py3.8.egg\tortoise\models\arch_util.py", line 341, in forward        
  File "C:\Anaconda3\envs\laver\lib\site-packages\torch\utils\checkpoint.py", line 235, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "C:\Anaconda3\envs\laver\lib\site-packages\torch\utils\checkpoint.py", line 96, in forward
    outputs = run_function(*args)
  File "C:\Anaconda3\envs\laver\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Anaconda3\envs\laver\lib\site-packages\tortoise-2.2.0-py3.8.egg\tortoise\models\xtransformers.py", line 709, in forward    
RuntimeError: CUDA out of memory. Tried to allocate 124.00 MiB (GPU 0; 4.00 GiB total capacity; 2.81 GiB already allocated; 0 bytes free; 2.93 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by vaibhav-s-dabhade** [comment]
> Hi there, Take a look at #21. Basically what is suggested is that you adjust `autoregressive_batch_size` down to 1.

Yes, It works only with autoregressive_batch_size = 1
