### ISSUE TITLE
Numpy long attribute

### ISSUE THREAD

**Issue by freezer7** [neonbjb/tortoise-tts#379]
Prefacing that I am absolutely not a techy person so this might be a silly question. I'm trying to run do_tts.py but I keep running into an error that has something to do with "numpy" not having the "long" attribute. I'm running windows, virtual environment with python 3.8. How do I fix this?

```
(ttsve) C:\Users\raspr\OneDrive\Desktop\tts stuff\tortoise-tts-main>python tortoise/do_tts.py --text "I'm going to speak this" --voice oscarisaac --preset fast
C:\Users\raspr\OneDrive\Desktop\tts stuff\ttsve\lib\site-packages\numba\types\__init__.py:110: FutureWarning: In the future `np.long` will be defined as the corresponding NumPy scalar.
  long_ = _make_signed(np.long)
Traceback (most recent call last):
  File "tortoise/do_tts.py", line 7, in <module>
    from api import TextToSpeech, MODELS_DIR
  File "C:\Users\raspr\OneDrive\Desktop\tts stuff\tortoise-tts-main\tortoise\api.py", line 22, in <module>
    from tortoise.utils.audio import wav_to_univnet_mel, denormalize_tacotron_mel
  File "C:\Users\raspr\OneDrive\Desktop\tts stuff\ttsve\lib\site-packages\tortoise-2.4.2-py3.8.egg\tortoise\utils\audio.py", line 4, in <module>
    import librosa
  File "C:\Users\raspr\OneDrive\Desktop\tts stuff\ttsve\lib\site-packages\librosa\__init__.py", line 209, in <module>
    from . import core
  File "C:\Users\raspr\OneDrive\Desktop\tts stuff\ttsve\lib\site-packages\librosa\core\__init__.py", line 5, in <module>    from .convert import *  # pylint: disable=wildcard-import
  File "C:\Users\raspr\OneDrive\Desktop\tts stuff\ttsve\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "C:\Users\raspr\OneDrive\Desktop\tts stuff\ttsve\lib\site-packages\librosa\core\notation.py", line 8, in <module>    from ..util.exceptions import ParameterError
  File "C:\Users\raspr\OneDrive\Desktop\tts stuff\ttsve\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\raspr\OneDrive\Desktop\tts stuff\ttsve\lib\site-packages\librosa\util\utils.py", line 9, in <module>
    import numba
  File "C:\Users\raspr\OneDrive\Desktop\tts stuff\ttsve\lib\site-packages\numba\__init__.py", line 15, in <module>
    from . import config, errors, _runtests as runtests, types
  File "C:\Users\raspr\OneDrive\Desktop\tts stuff\ttsve\lib\site-packages\numba\types\__init__.py", line 110, in <module>
    long_ = _make_signed(np.long)
  File "C:\Users\raspr\OneDrive\Desktop\tts stuff\ttsve\lib\site-packages\numpy\__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'long'
```

**Comment by Amadar85** [comment]
same.

**Comment by windowpane** [comment]
I was able to solve it by doing:

``` bash
pip install numpy==1.20.0
```
