### ISSUE TITLE
ImportError: Numba requires at least version 0.40.0 of llvmlite.

### ISSUE THREAD

**Issue by todd0x** [neonbjb/tortoise-tts#395]
ImportError: Numba requires at least version 0.40.0 of llvmlite.
Installed version is 0.39.1.
Please update llvmlite.

originally i got this error:

ImportError: Numba requires at least version 14.0.0 of LLVM.
Installed llvmlite is built against version 11.1.0.
Please update llvmlite.

so i used the command conda install llvmlite

now im getting the error 

(base) C:\Users\PC\tortoise-tts>python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast
Traceback (most recent call last):
  File "C:\Users\PC\tortoise-tts\tortoise\do_tts.py", line 7, in <module>
    from api import TextToSpeech, MODELS_DIR
  File "C:\Users\PC\tortoise-tts\tortoise\api.py", line 22, in <module>
    from tortoise.utils.audio import wav_to_univnet_mel, denormalize_tacotron_mel
  File "C:\Users\PC\miniconda3\lib\site-packages\tortoise-2.4.2-py3.10.egg\tortoise\utils\audio.py", line 10, in <module>
    from tortoise.utils.stft import STFT
  File "C:\Users\PC\miniconda3\lib\site-packages\tortoise-2.4.2-py3.10.egg\tortoise\utils\stft.py", line 38, in <module>
    from librosa.util import pad_center, tiny
  File "C:\Users\PC\miniconda3\lib\site-packages\lazy_loader-0.2-py3.10.egg\lazy_loader\__init__.py", line 76, in __getattr__
    submod = importlib.import_module(submod_path)
  File "C:\Users\PC\miniconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\PC\miniconda3\lib\site-packages\librosa-0.10.0.post2-py3.10.egg\librosa\util\utils.py", line 11, in <module>
    import numba
  File "C:\Users\PC\miniconda3\lib\site-packages\numba-0.57.0rc1-py3.10-win-amd64.egg\numba\__init__.py", line 231, in <module>
    _ensure_llvm()
  File "C:\Users\PC\miniconda3\lib\site-packages\numba-0.57.0rc1-py3.10-win-amd64.egg\numba\__init__.py", line 167, in _ensure_llvm
    raise ImportError(msg)
ImportError: Numba requires at least version 0.40.0 of llvmlite.
Installed version is 0.39.1.
Please update llvmlite.

**Comment by JackB296** [comment]
conda install --channel=numba llvmlite

seemed to work for me
