### ISSUE TITLE
Please follow this installation guide 

### ISSUE THREAD

**Issue by CodexOmega** [neonbjb/tortoise-tts#422]
For all the people having issues getting this working i would advise following this install guide. It's easier for me just post video video link instead of trying to explain, It is working flawlessly for me now. :)

https://www.youtube.com/watch?v=hOSsGOmDC3w

**Comment by Stormthirst** [comment]
I followed the video, which got me a lot further than I managed before, but it's giving me a run time error:

Traceback (most recent call last):
  File "C:\Users\andrew\anaconda3\tortoise-tts\tortoise\do_tts.py", line 7, in <module>
    from api import TextToSpeech, MODELS_DIR
  File "C:\Users\andrew\anaconda3\tortoise-tts\tortoise\api.py", line 24, in <module>
    from tortoise.utils.tokenizer import VoiceBpeTokenizer
  File "C:\Users\andrew\anaconda3\envs\tortoise-tts\lib\site-packages\tortoise-2.4.2-py3.9.egg\tortoise\utils\tokenizer.py", line 4, in <module>
    import inflect
  File "C:\Users\andrew\anaconda3\envs\tortoise-tts\lib\site-packages\inflect-6.0.4-py3.9.egg\inflect\__init__.py", line 77, in <module>
    from pydantic.typing import Annotated
ImportError: cannot import name 'Annotated' from 'pydantic.typing' (C:\Users\andrew\anaconda3\envs\tortoise-tts\lib\site-packages\pydantic-2.0a3-py3.9.egg\pydantic\typing.py)

What am I missing?

**Comment by GiveMeCodingHelp** [comment]
@Stormthirst 
try
```
pip uninstall pydantic
```
```
pip install pydantic==1.9.1
```

**Comment by Stormthirst** [comment]
> @Stormthirst try
> 
> ```
> pip uninstall pydantic
> ```
> 
> ```
> pip install pydantic==1.9.1
> ```

That worked! Thank you so much!

**Comment by Magenta-6** [comment]
@GiveMeCodingHelp  Ditto error for me too!

  File "C:\Users\XYZ\anaconda3\envs\tortoise-tts\lib\site-packages\inflect-6.0.4-py3.10.egg\inflect\__init__.py", line 77, in <module>
    from pydantic.typing import Annotated
ImportError: cannot import name 'Annotated' from 'pydantic.typing' (C:\Users\XYZ\anaconda3\envs\tortoise-tts\lib\site-packages\pydantic-2.0b2-py3.10.egg\pydantic\typing.py)

Your solution worked also for me! Thanks
