### ISSUE TITLE
I have a trained voice pt file. when generating voice should i provide original training dataset sound too? does it matter or improve?

### ISSUE THREAD

**Issue by FurkanGozukara** [neonbjb/tortoise-tts#436]
I have a trained voice pt file. when generating voice should i provide original training dataset sound too? does it matter or improve?

It is working very well

By the way i am using this branch

https://github.com/152334H/tortoise-tts-fast

it has this option

    voices_dir: Optional[str] = field(default=None, alias=["-V"])
    """Path to directory containing extra voices to be loaded. Use a comma to specify multiple directories."""

does that mean it is our training voices?

I use this command and it is working

`tortoise_tts.py --diffusion_iterations 500 --seed 1 --preset fast --ar_checkpoint "F:\DL-Art-School\experiments\test2\models\1480_gpt.pth" --text_split "gg"`

so what other parameters i can add to improve

**Comment by theymightbedavis** [comment]
Hi Dr. Gozukara, can you please tell me more details of how you were able to use your pre-trained pth file?

I am trying to use a pre-trained pth file as well, but I am not able to make it work with tortoise tts.  I have tried to place the pth file in its own folder within the "voices" folder.  I then used the following code:

voice = 'mycustomvoice' #@param {type:"string"}
#my pth is in the folder mycustomvoice within the voices folder

voice_samples, conditioning_latents = load_voice(voice)
gen = tts.tts_with_preset(text, voice_samples=voice_samples, conditioning_latents=conditioning_latents, 
                          preset=preset)
torchaudio.save('generated.wav', gen.squeeze(0).cpu(), 24000)
IPython.display.Audio('generated.wav')

This code works when I use a voice folder which has wav files in it.  But if I use the folder which has the pth file, it does not work.

Can you please advise on how you were able to get it working with your pth file?

**Comment by FurkanGozukara** [comment]
> Hi Dr. Gozukara, can you please tell me more details of how you were able to use your pre-trained pth file?
> 
> I am trying to use a pre-trained pth file as well, but I am not able to make it work with tortoise tts. I have tried to place the pth file in its own folder within the "voices" folder. I then used the following code:
> 
> voice = 'mycustomvoice' #@param {type:"string"} #my pth is in the folder mycustomvoice within the voices folder
> 
> voice_samples, conditioning_latents = load_voice(voice) gen = tts.tts_with_preset(text, voice_samples=voice_samples, conditioning_latents=conditioning_latents, preset=preset) torchaudio.save('generated.wav', gen.squeeze(0).cpu(), 24000) IPython.display.Audio('generated.wav')
> 
> This code works when I use a voice folder which has wav files in it. But if I use the folder which has the pth file, it does not work.
> 
> Can you please advise on how you were able to get it working with your pth file?

here my full tutorial for this

https://youtu.be/OiMRlqcgDL0

**Comment by theymightbedavis** [comment]
Thank you so much for your reply and for the excellent and in depth tutorial.

I'm afraid I have still encountered a problem.  I am attempting to run the code in a Kaggle notebook, and I have followed your instructions from your Github page in Part 3, to install Tortoise TTS and the necessary other elements.

However, when I try to use the line to generate audio, with an ar_checkpoint referencing to my pth file, I run into this problem:

/kaggle/working/tortoise-tts-fast/scripts
/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/opt/conda/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/opt/conda/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Loading tts...
Traceback (most recent call last):
  File "/kaggle/working/tortoise-tts-fast/scripts/tortoise_tts.py", line 280, in <module>
    tts = TextToSpeech(
  File "/kaggle/working/tortoise-tts-fast/tortoise/api.py", line 271, in __init__
    self.autoregressive.load_state_dict(torch.load(ar_path))
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UnifiedVoice:
	Missing key(s) in state_dict: "conditioning_encoder.init.weight", "conditioning_encoder.init.bias", [and then a lot of other items which are similar]
	

Is my problem the NumPy version?
When you ran the line in your video, the first line in output was "Loading tts..."

I anticipated that maybe the problem was related to kaggle not running virtual environments the same way as on a local machine, so I then tried it again with some adaptations to make sure the virtual environment was running in each kaggle code cell, but I still ended with the same error.

Can you please have a look at the error and tell me what you think might be the problem?

**Comment by FurkanGozukara** [comment]
> Thank you so much for your reply and for the excellent and in depth tutorial.
> 
> I'm afraid I have still encountered a problem. I am attempting to run the code in a Kaggle notebook, and I have followed your instructions from your Github page in Part 3, to install Tortoise TTS and the necessary other elements.
> 
> However, when I try to use the code you provided (with necessary edits for location of my pth file) to generate audio, with an ar_checkpoint referencing to my pth file, I run into this problem:
> 
> /kaggle/working/tortoise-tts-fast/scripts /opt/conda/lib/python3.10/site-packages/scipy/**init**.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5 warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}" /opt/conda/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/opt/conda/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source? warn( Loading tts... Traceback (most recent call last): File "/kaggle/working/tortoise-tts-fast/scripts/tortoise_tts.py", line 280, in tts = TextToSpeech( File "/kaggle/working/tortoise-tts-fast/tortoise/api.py", line 271, in **init** self.autoregressive.load_state_dict(torch.load(ar_path)) File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for UnifiedVoice: Missing key(s) in state_dict: "conditioning_encoder.init.weight", "conditioning_encoder.init.bias", [and then a lot of other items which are similar]
> 
> Is my problem the NumPy version? When you ran the line in your video, the first line in output was "Loading tts..."
> 
> I anticipated that maybe the problem was related to kaggle not running virtual environments the same way as on a local machine, so I then tried it again with some adaptations to make sure the virtual environment was running in each kaggle code cell, but I still ended with the same error.
> 
> Can you please have a look at the error and tell me what you think might be the problem?

kaggle is so painful. it doesnt allow venv

i yesterday worked like a day for another repo to work but didnt work. 

good luck

**Comment by theymightbedavis** [comment]
Thank you for looking at this!  I really am stumped as to how to make progress here.

I have now attempted to do it on my local computer (to avoid Kaggle and Colab), so that I can properly use virtual environments.

However, I have reached the same error after running the generation line "python tortoise_tts.py --preset fast...":

Traceback (most recent call last):
File "[my  folders]\tortoise-tts-fast\scripts\tortoise_tts.py", line 280, in
tts = TextToSpeech(
File "[my  folders]\tortoise-tts-fast\tortoise\api.py", line 271, in init
self.autoregressive.load_state_dict(torch.load(ar_path))
File "[my  folders]\anaconda3\envs\tts\lib\site-packages\torch\nn\modules\module.py", line 1671, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UnifiedVoice:
Missing key(s) in state_dict: "conditioning_encoder.init.weight", "conditioning_encoder.init.bias", [and the other items]

In this case, I have used Anaconda to create a virtual environment, instead of the "python - venv venv" line which you used (because when I try to run the "pip3 install torch==1.13.1..." line within the venv environment, I keep getting an error saying that it could not find a version that satisfies the requirement torch==1.13.1.  I used "conda create --name tts python=3.10" to create the virtual environment, and then the the install for torch 1.13.1 line worked successfully.)

I'm rather stumped, because I am following your instructions, and using the local machine now, but still getting the same error.  Can you please tell me if you have any ideas for this?

**Comment by FurkanGozukara** [comment]
> Thank you for looking at this! I really am stumped as to how to make progress here.
> 
> I have now attempted to do it on my local computer (to avoid Kaggle and Colab), so that I can properly use virtual environments.
> 
> However, I have reached the same error after running the generation line "python tortoise_tts.py --preset fast...":
> 
> Traceback (most recent call last): File "[my folders]\tortoise-tts-fast\scripts\tortoise_tts.py", line 280, in tts = TextToSpeech( File "[my folders]\tortoise-tts-fast\tortoise\api.py", line 271, in init self.autoregressive.load_state_dict(torch.load(ar_path)) File "[my folders]\anaconda3\envs\tts\lib\site-packages\torch\nn\modules\module.py", line 1671, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for UnifiedVoice: Missing key(s) in state_dict: "conditioning_encoder.init.weight", "conditioning_encoder.init.bias", [and the other items]
> 
> In this case, I have used Anaconda to create a virtual environment, instead of the "python - venv venv" line which you used (because when I try to run the "pip3 install torch==1.13.1..." line within the venv environment, I keep getting an error saying that it could not find a version that satisfies the requirement torch==1.13.1. I used "conda create --name tts python=3.10" to create the virtual environment, and then the the install for torch 1.13.1 line worked successfully.)
> 
> I'm rather stumped, because I am following your instructions, and using the local machine now, but still getting the same error. Can you please tell me if you have any ideas for this?
> 
> I should mention that my Python is version 3.10.6.

https://www.patreon.com/posts/tortoise-tts-tts-90496485

Download the attached [install.bat] and [activate.bat] and put them into a folder (no SPACES or non-English characters super important, e.g.: bg_replace) where you want to install.

![image](https://github.com/neonbjb/tortoise-tts/assets/19240467/d649f375-8702-4ec1-b2f2-4eda1fee75e7)

![image](https://github.com/neonbjb/tortoise-tts/assets/19240467/c59b2c3a-deba-4bee-a270-fff46114dfbe)

![image](https://github.com/neonbjb/tortoise-tts/assets/19240467/cadb0312-d374-4dff-ba1b-8cec270ea25b)


if it doesn't work for some reason i will fix. but last time i tried was working great
