### ISSUE TITLE
torch.cuda.OutOfMemoryError on older GPU

### ISSUE THREAD

**Issue by xelibrion** [neonbjb/tortoise-tts#439]
Hi, I'm trying to run a samplg generation using `do_tts.py` and I ran into memory issues on my 11GB GTX 1080 Ti (old, I know). 
There seem to be enough memory to run the inference - wondering if the error might be caused by the lack of AMP support in my older GPU? Or would it be something else?

```
tortoise-tts ➜ python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast               
Generating autoregressive samples..
100%|█████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:29<00:00,  2.48s/it]
Computing best candidates using CLVP
|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |    972 MiB |   2160 MiB |   1358 GiB |   1358 GiB |
|       from large pool |    970 MiB |   2125 MiB |   1217 GiB |   1216 GiB |
|       from small pool |      2 MiB |     43 MiB |    141 GiB |    141 GiB |
|---------------------------------------------------------------------------|
| Active memory         |    972 MiB |   2160 MiB |   1358 GiB |   1358 GiB |
|       from large pool |    970 MiB |   2125 MiB |   1217 GiB |   1216 GiB |
|       from small pool |      2 MiB |     43 MiB |    141 GiB |    141 GiB |
|---------------------------------------------------------------------------|
| Requested memory      |    938 MiB |   2157 MiB |   1308 GiB |   1307 GiB |
|       from large pool |    936 MiB |   2122 MiB |   1167 GiB |   1166 GiB |
|       from small pool |      2 MiB |     43 MiB |    141 GiB |    141 GiB |
|---------------------------------------------------------------------------|
| GPU reserved memory   |   2350 MiB |   2350 MiB |   2350 MiB |      0 B   |
|       from large pool |   2304 MiB |   2304 MiB |   2304 MiB |      0 B   |
|       from small pool |     46 MiB |     46 MiB |     46 MiB |      0 B   |
|---------------------------------------------------------------------------|
| Non-releasable memory |  21860 KiB | 233529 KiB |   1561 GiB |   1561 GiB |
|       from large pool |  19968 KiB | 231827 KiB |   1411 GiB |   1411 GiB |
|       from small pool |   1892 KiB |   9554 KiB |    150 GiB |    150 GiB |
|---------------------------------------------------------------------------|
| Allocations           |     468    |     574    |  672370    |  671902    |
|       from large pool |     244    |     244    |  351772    |  351528    |
|       from small pool |     224    |     374    |  320598    |  320374    |
|---------------------------------------------------------------------------|
| Active allocs         |     468    |     574    |  672370    |  671902    |
|       from large pool |     244    |     244    |  351772    |  351528    |
|       from small pool |     224    |     374    |  320598    |  320374    |
|---------------------------------------------------------------------------|
| GPU reserved segments |     156    |     156    |     156    |       0    |
|       from large pool |     133    |     133    |     133    |       0    |
|       from small pool |      23    |      23    |      23    |       0    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |       6    |      58    |  387241    |  387235    |
|       from large pool |       3    |      39    |  209344    |  209341    |
|       from small pool |       3    |      27    |  177897    |  177894    |
|---------------------------------------------------------------------------|
| Oversize allocations  |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize GPU segments |       0    |       0    |       0    |       0    |
|===========================================================================|

  0%|                                                                                              | 0/12 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/xelibrion/projects/tortoise-tts/tortoise/do_tts.py", line 37, in <module>
    gen, dbg_state = tts.tts_with_preset(args.text, k=args.candidates, voice_samples=voice_samples, conditioning_latents=conditioning_latents,
  File "/home/xelibrion/projects/tortoise-tts/tortoise/api.py", line 483, in tts_with_preset
    return self.tts(text, **settings)
  File "/home/xelibrion/projects/tortoise-tts/tortoise/api.py", line 634, in tts
    clvp = self.clvp(
  File "/home/xelibrion/anaconda3/envs/tortoise-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xelibrion/projects/tortoise-tts/tortoise/models/clvp.py", line 121, in forward
    enc_speech = self.speech_transformer(speech_emb, mask=voice_mask)
  File "/home/xelibrion/anaconda3/envs/tortoise-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xelibrion/projects/tortoise-tts/tortoise/models/arch_util.py", line 368, in forward
    h = self.transformer(x, **kwargs)
  File "/home/xelibrion/anaconda3/envs/tortoise-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xelibrion/projects/tortoise-tts/tortoise/models/xtransformers.py", line 1233, in forward
    x, intermediates = self.attn_layers(x, mask=mask, mems=mems, return_hiddens=True, **kwargs)
  File "/home/xelibrion/anaconda3/envs/tortoise-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xelibrion/projects/tortoise-tts/tortoise/models/xtransformers.py", line 968, in forward
    out, inter, k, v = block(x, None, mask, None, attn_mask, self.pia_pos_emb, rotary_pos_emb,
  File "/home/xelibrion/anaconda3/envs/tortoise-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xelibrion/projects/tortoise-tts/tortoise/models/arch_util.py", line 345, in forward
    return partial(x, *args)
  File "/home/xelibrion/anaconda3/envs/tortoise-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xelibrion/projects/tortoise-tts/tortoise/models/xtransformers.py", line 705, in forward
    post_softmax_attn = attn.clone()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 92.00 MiB (GPU 0; 10.91 GiB total capacity; 4.35 GiB already allocated; 25.62 MiB free; 4.81 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by neonbjb** [comment]
This should run on a 1080ti without any problems, I think you have some other program running and taking up your vram.

**Comment by xelibrion** [comment]
@neonbjb indeed, had a jupyter session hanging, thanks!
