### ISSUE TITLE
Model error

### ISSUE THREAD

**Issue by badAt-Everything** [neonbjb/tortoise-tts#476]
I was trying to test my installation of TortoiseTTS using this command-

D:\tortoise-tts>python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast

And I got this error:

Traceback (most recent call last):
  File "D:\tortoise-tts\tortoise\do_tts.py", line 27, in <module>
    tts = TextToSpeech(models_dir=args.model_dir)
  File "D:\tortoise-tts\tortoise\api.py", line 231, in \__init__
    self.autoregressive.load_state_dict(torch.load(get_model_path('autoregressive.pth', models_dir)))
  File "D:\Users\\_(my user)_\anaconda3\envs\voiceclone\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UnifiedVoice:
        Unexpected key(s) in state_dict: "gpt.h.0.attn.bias", "gpt.h.0.attn.masked_bias", "gpt.h.1.attn.bias", "gpt.h.1.attn.masked_bias", "gpt.h.2.attn.bias", "gpt.h.2.attn.masked_bias", "gpt.h.3.attn.bias", "gpt.h.3.attn.masked_bias", "gpt.h.4.attn.bias", "gpt.h.4.attn.masked_bias", "gpt.h.5.attn.bias", "gpt.h.5.attn.masked_bias", "gpt.h.6.attn.bias", "gpt.h.6.attn.masked_bias", "gpt.h.7.attn.bias", "gpt.h.7.attn.masked_bias", "gpt.h.8.attn.bias", "gpt.h.8.attn.masked_bias", "gpt.h.9.attn.bias", "gpt.h.9.attn.masked_bias", "gpt.h.10.attn.bias", "gpt.h.10.attn.masked_bias", "gpt.h.11.attn.bias", "gpt.h.11.attn.masked_bias", "gpt.h.12.attn.bias", "gpt.h.12.attn.masked_bias", "gpt.h.13.attn.bias", "gpt.h.13.attn.masked_bias", "gpt.h.14.attn.bias", "gpt.h.14.attn.masked_bias", "gpt.h.15.attn.bias", "gpt.h.15.attn.masked_bias", "gpt.h.16.attn.bias", "gpt.h.16.attn.masked_bias", "gpt.h.17.attn.bias", "gpt.h.17.attn.masked_bias", "gpt.h.18.attn.bias", "gpt.h.18.attn.masked_bias", "gpt.h.19.attn.bias", "gpt.h.19.attn.masked_bias", "gpt.h.20.attn.bias", "gpt.h.20.attn.masked_bias", "gpt.h.21.attn.bias", "gpt.h.21.attn.masked_bias", "gpt.h.22.attn.bias", "gpt.h.22.attn.masked_bias", "gpt.h.23.attn.bias", "gpt.h.23.attn.masked_bias", "gpt.h.24.attn.bias", "gpt.h.24.attn.masked_bias", "gpt.h.25.attn.bias", "gpt.h.25.attn.masked_bias", "gpt.h.26.attn.bias", "gpt.h.26.attn.masked_bias", "gpt.h.27.attn.bias", "gpt.h.27.attn.masked_bias", "gpt.h.28.attn.bias", "gpt.h.28.attn.masked_bias", "gpt.h.29.attn.bias", "gpt.h.29.attn.masked_bias".

Also, one of the packages in requirements.txt wasn't installing with Pip (Python.exe failed), so I installed it with Conda instead.

**Comment by ic41** [comment]
Same error here on both Windows 10 and Windows 11, using n8bot's conda installation instructions: https://gist.github.com/n8bot/96f5a7c5a9493909113280cfa9732506

**Comment by DRob81** [comment]
It is quite simple. Use transformers==4.19. Not any newer version and it will work. Tried myself with python 3.11 on Windows 11 and it works perfectly.

**Comment by ic41** [comment]
I initially got errors when I attempted to do conda install transformers=4.19 -- couldn't find it -- so I had to download this: https://anaconda.org/conda-forge/transformers/4.19.4/download/noarch/transformers-4.19.4-pyhd8ed1ab_0.tar.bz2

Then in my activated tortoise environment I had to do:
`conda install [path-to-downloaded-file]`

Then, for some reason I had to:
`conda install transformers=4.19`

And then for some reason it worked, and then I could use tortoise like normal.

I'm too much of a noob to understand why it this sequence worked, but I got output.
