### ISSUE TITLE
Building wheel for llvmlite (setup.py) ... error

### ISSUE THREAD

**Issue by KenDoStudios** [neonbjb/tortoise-tts#482]
on step 1 and i got an error  
  
  Building wheel for llvmlite (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      C:\Users\(name)\AppData\Roaming\Python\Python39\site-packages\setuptools\__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      C:\ProgramData\miniconda3\python.exe "C:\Users\name\AppData\Local\Temp\pip-install-mofq2agi\llvmlite_1d75823c1daa4e91ae8380310b7c2831\ffi\build.py"
      Trying generator 'Visual Studio 14 2015 Win64'
      Traceback (most recent call last):
        File "C:\Users\name\AppData\Local\Temp\pip-install-mofq2agi\llvmlite_1d75823c1daa4e91ae8380310b7c2831\ffi\build.py", line 168, in <module>
          main()
        File "C:\Users\name\AppData\Local\Temp\pip-install-mofq2agi\llvmlite_1d75823c1daa4e91ae8380310b7c2831\ffi\build.py", line 156, in main
          main_win32()
        File "C:\Users\name\AppData\Local\Temp\pip-install-mofq2agi\llvmlite_1d75823c1daa4e91ae8380310b7c2831\ffi\build.py", line 88, in main_win32
          generator = find_win32_generator()
        File "C:\Users\name\AppData\Local\Temp\pip-install-mofq2agi\llvmlite_1d75823c1daa4e91ae8380310b7c2831\ffi\build.py", line 76, in find_win32_generator
          try_cmake(cmake_dir, build_dir, generator)
        File "C:\Users\name\AppData\Local\Temp\pip-install-mofq2agi\llvmlite_1d75823c1daa4e91ae8380310b7c2831\ffi\build.py", line 28, in try_cmake
          subprocess.check_call(['cmake', '-G', generator, cmake_dir])
        File "C:\ProgramData\miniconda3\lib\subprocess.py", line 368, in check_call
          retcode = call(*popenargs, **kwargs)
        File "C:\ProgramData\miniconda3\lib\subprocess.py", line 349, in call
          with Popen(*popenargs, **kwargs) as p:
        File "C:\ProgramData\miniconda3\lib\subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\ProgramData\miniconda3\lib\subprocess.py", line 1420, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      error: command 'C:\\ProgramData\\miniconda3\\python.exe' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Successfully built numba progressbar ffmpeg
Failed to build llvmlite
ERROR: Could not build wheels for llvmlite, which is required to install pyproject.toml-based projects

**Comment by KenDoStudios** [comment]
i tried to install the pip and it says its here already
Requirement already satisfied: llvmlite in c:\users\kenneth apthorp\appdata\roaming\python\python39\site-packages (0.39.0)

**Comment by KenDoStudios** [comment]
i also tried to install LLVM from the official website: http://llvm.org/releases/download.html it still is the same error

**Comment by vonsuu** [comment]
I had the same issue, tried the same what you mentioned and also didn't helped. In the end created new conda env with python 3.8 and finally installed without any problems.

**Comment by KenDoStudios** [comment]
how do i do that? @vonsuu
