### ISSUE TITLE
ModuleNotFoundError: No module named 'tortoise'

### ISSUE THREAD

**Issue by Vyiell** [neonbjb/tortoise-tts#486]
I am trying to install the AI voice cloning software. When I try to run .\start.bat , I get this error:

Traceback (most recent call last):
  File "C:\Users\user\Downloads\Voices\ai-voice-cloning\src\main.py", line 11, in <module>
    from utils import *
  File "C:\Users\user\Downloads\Voices\ai-voice-cloning\src\utils.py", line 40, in <module>
    from tortoise.api import TextToSpeech as TorToise_TTS, MODELS, get_model_path, pad_or_truncate
ModuleNotFoundError: No module named 'tortoise'

Anyone know how to fix this issue?

**Comment by yesbroc** [comment]
pip install tortoise

**Comment by Radriel** [comment]
> pip install tortoise

This did not solve the issue :(

**Comment by salftish** [comment]
pip install tortoise-orm

**Comment by fakerybakery** [comment]
@salftish @Radriel the neither the `tortoise` nor `tortoise-orm` packages are affiliated with Tortoise TTS.

Please run:
```
pip install tortoise-tts
```
instead.

**Comment by anoneditor** [comment]
could you fix it؟؟ I have the same problem, I tried the above methods, but it didn't open😐

**Comment by whok1lledkenny** [comment]
Add to your start.bat:``

**Comment by whok1lledkenny** [comment]
Try add this to your bat file
`call .\venv\Scripts\activate.bat
python -m pip install -e .\modules\tortoise-tts\`
Works for me

**Comment by whok1lledkenny** [comment]
Try add this to your bat file
`call .\venv\Scripts\activate.bat
python -m pip install -e .\modules\tortoise-tts\`
Works for me
