### ISSUE TITLE
RuntimeError: stack expects a non-empty TensorList

### ISSUE THREAD

**Issue by noahschulman14** [neonbjb/tortoise-tts#487]
Hello, I am getting the following error when trying to use tortoise. Everything used to work fine for me.

Here is the stack trace:

Traceback (most recent call last):
  File "/mnt/MFC_deepfake_data/ntest/tortoise/tortoise-stuff/tortoise-tts/tts.py", line 36, in <module>
    gen = tts.tts_with_preset(text, voice_samples=voice_samples, conditioning_latents=conditioning_latents, preset=preset)
  File "/mnt/MFC_deepfake_data/ntest/tortoise/tortoise-stuff/tortoise-tts/tortoise/api.py", line 328, in tts_with_preset
    return self.tts(text, **settings)
  File "/mnt/MFC_deepfake_data/ntest/tortoise/tortoise-stuff/tortoise-tts/tortoise/api.py", line 393, in tts
    auto_conditioning, diffusion_conditioning, auto_conds, _ = self.get_conditioning_latents(voice_samples, return_mels=True)
  File "/mnt/MFC_deepfake_data/ntest/tortoise/tortoise-stuff/tortoise-tts/tortoise/api.py", line 274, in get_conditioning_latents
    auto_conds = torch.stack(auto_conds, dim=1)
RuntimeError: stack expects a non-empty TensorList

Any help would be much appreciated!!!

**Comment by riazkhawaja** [comment]
Are you using a .wav file?

**Comment by Zeon8985Army** [comment]
In my condition, my reference voice is empty

**Comment by baptx** [comment]
@riazkhawaja Thanks, the problem was indeed that I was not using a WAV file. It could be useful if other files like OGG are supported (for example by converting them automatically if needed) like done for another project https://github.com/serp-ai/bark-with-voice-clone.
