### ISSUE TITLE
traceback of an error i'm having

### ISSUE THREAD

**Issue by PALKIP** [neonbjb/tortoise-tts#489]
i'm not familiar with this stuff so i have no idea what to do really,
i installed everything just fine, then executed the command:
`python tortoise/do_tts.py --text "bla bla bla" --voice random --preset fast`

and now i'm facing this error message
```
Traceback (most recent call last):
  File "X:\TortoiseTTS\tortoise-tts\tortoise\do_tts.py", line 27, in <module>
    tts = TextToSpeech(models_dir=args.model_dir)
  File "X:\TortoiseTTS\tortoise-tts\tortoise\api.py", line 231, in __init__
    self.autoregressive.load_state_dict(torch.load(get_model_path('autoregressive.pth', models_dir)))
  File "X:\conda\envs\tortoise\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "X:\conda\envs\tortoise\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

**Comment by giovannilima262** [comment]
I have the same error

**Comment by MahmoudMousaHamad** [comment]
Me too

**Comment by manmay-nakhashi** [comment]
can you try changing this to AutoModelForCTC https://github.com/neonbjb/tortoise-tts/blob/3c4d9c51316cd2421cc2dea11ac3a7a2d3394acd/tortoise/utils/wav2vec_alignment.py#L53C22-L53C36
also don't forget to import AutoModelForCTC
