### ISSUE TITLE
Error after running the code

### ISSUE THREAD

**Issue by YoruNoKen** [neonbjb/tortoise-tts#496]
I should have installed all the requirements, yet I get this error:

```
(base) C:\Users\mffet\tortoise-tts>  python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast
C:\Users\mffet\anaconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Traceback (most recent call last):
  File "C:\Users\mffet\tortoise-tts\tortoise\do_tts.py", line 27, in <module>
    tts = TextToSpeech(models_dir=args.model_dir)
  File "C:\Users\mffet\tortoise-tts\tortoise\api.py", line 231, in __init__
    self.autoregressive.load_state_dict(torch.load(get_model_path('autoregressive.pth', models_dir)))
  File "C:\Users\mffet\anaconda3\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\mffet\anaconda3\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

**Comment by manmay-nakhashi** [comment]
@YoruNoKen download autoregrassive model again. make sure you are using python 3.9.10

**Comment by giovannilima262** [comment]
I have the same error using python version 3.9.17
