### ISSUE TITLE
%1 is not a valid Win32 application. Error loading torch\lib\nvfuser_codegen.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by izzymice** [neonbjb/tortoise-tts#498]
`(tortoise) C:\Users\ash\Downloads\tortoise-tts>python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast
Traceback (most recent call last):
  File "C:\Users\ash\Downloads\tortoise-tts\tortoise\do_tts.py", line 4, in <module>
    import torch
  File "C:\Users\ash\.conda\envs\tortoise\lib\site-packages\torch\__init__.py", line 122, in <module>
    raise err
OSError: [WinError 193] %1 is not a valid Win32 application. Error loading "C:\Users\ash\.conda\envs\tortoise\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.`

while running
`python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast`

**Comment by jmcgover** [comment]
+1

**Comment by jmcgover** [comment]
My working theory is that is has something to do with having Python 3.11 installed and the Python 3.11 version of anaconda installed, when the repo only mentions Python 3.9. Unfortunately, testing this might mean uninstalling 3.11 everywhere I can can then reinstall everything, targeting 3.9 versions of everything.

**Comment by SAA7777777** [comment]
> My working theory is that is has something to do with having Python 3.11 installed and the Python 3.11 version of anaconda installed, when the repo only mentions Python 3.9. Unfortunately, testing this might mean uninstalling 3.11 everywhere I can and then reinstalling it all, targeting 3.9 versions of everything.

I notice this problem, and I registered Anaconda as my default Python 3.11 when I installed anaconda, but the version of cuda and pytorch I chosen are python 3.10, do you think this will cause this problem. If it does, how can I solve? reinstalled anaconda but not to choose anaconda as my default python 3.11?

**Comment by jmcgover** [comment]
> > My working theory is that is has something to do with having Python 3.11 installed and the Python 3.11 version of anaconda installed, when the repo only mentions Python 3.9. Unfortunately, testing this might mean uninstalling 3.11 everywhere I can and then reinstalling it all, targeting 3.9 versions of everything.
> 
> I notice this problem, and I registered Anaconda as my default Python 3.11 when I installed anaconda, but the version of cuda and pytorch I chosen are python 3.10, do you think this will cause this problem.

Most likely, I think.

>  If it does, how can I solve? reinstalled anaconda but not to choose anaconda as my default python 3.11?

I believe I ended up uninstalling all of my Python's (quit a few times) and targeting everything to 3.9, like you mentioned in the other comment.
