### ISSUE TITLE
Cannot do do_tts thing

### ISSUE THREAD

**Issue by maxi74x1** [neonbjb/tortoise-tts#502]
i keep getting the same error
i have done all the config and installation stuff but this keeps popping up
HELP PLEASE

![image](https://github.com/neonbjb/tortoise-tts/assets/119416285/ac3142a3-2b9f-434e-89a5-e6acf114ae58)

**Comment by natlamir** [comment]
looks like you might need to cd into the directory if you have already cloned it from the install steps, after you install pytorch, and trasformers, etc than cd to the repo once cloned, and proceed from there, etc:

git clone https://github.com/neonbjb/tortoise-tts.git
cd tortoise-tts

**Comment by NBNew** [comment]
Hello @neonbjb , thanks for this guide on tortoise-tts installation. I am not a pro here and have encountered an error. Would appreciate if you could help me figure out the issue here

I followed the steps below without any issue

conda create --name tortoise python=3.9 numba inflect
conda activate tortoise
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
conda install transformers=4.29.2
git clone https://github.com/neonbjb/tortoise-tts.git
cd tortoise-tts
python setup.py install

When I tried to run this command "python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast" I got error saying no module found "torchaudio"

To resolve the above I separately installed torchaudio using "pip install torchaudio" and it was successful

Now, when I am running "python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast" again, it throws below error. Could you please help me figure out what could be the issue here? 

(tortoise) nbano@Nasims-MacBook-Pro tortoise-tts % python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast

Traceback (most recent call last):
  File "/Users/nbano/tortoise-tts/tortoise/do_tts.py", line 5, in <module>
    import torchaudio
  File "/Users/nbano/miniconda3/envs/tortoise/lib/python3.10/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/Users/nbano/miniconda3/envs/tortoise/lib/python3.10/site-packages/torchaudio/_extension/__init__.py", line 43, in <module>
    _load_lib("libtorchaudio")
  File "/Users/nbano/miniconda3/envs/tortoise/lib/python3.10/site-packages/torchaudio/_extension/utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "/Users/nbano/miniconda3/envs/tortoise/lib/python3.10/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/Users/nbano/miniconda3/envs/tortoise/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/nbano/miniconda3/envs/tortoise/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so, 0x0006): Symbol not found: __ZN2at8internal15invoke_parallelExxxRKNSt3__18functionIFvxxEEE
  Referenced from: <297B3EE6-D4F0-328A-9434-2AC47E280C2D> /Users/nbano/miniconda3/envs/tortoise/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so
  Expected in:     <9DDA9B08-547F-32F9-87F1-796977059897> /Users/nbano/miniconda3/envs/tortoise/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib
(tortoise) nbano@Nasims-MacBook-Pro tortoise-tts %

**Comment by NBNew** [comment]
Quick update: After some effort and looking into resolution for issue #196, I am able to run tortoise-tts locally now. Just focusing on enhancing the voice quality
