### ISSUE TITLE
First do_tts execution traceback error

### ISSUE THREAD

**Issue by andresopeth** [neonbjb/tortoise-tts#512]
I'm trying to get Tortoise to work locally following the install steps, but on first execution I'm getting the following error, how can I fix it?. 

(tortoise) C:\Users\Usuario\tortoise-tts>python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast

`Traceback (most recent call last):
  File "C:\Users\Usuario\tortoise-tts\tortoise\do_tts.py", line 7, in <module>
    from api import TextToSpeech, MODELS_DIR
  File "C:\Users\Usuario\tortoise-tts\tortoise\api.py", line 14, in <module>
    from tortoise.models.autoregressive import UnifiedVoice
  File "C:\Users\Usuario\miniconda3\envs\tortoise\lib\site-packages\tortoise-2.4.2-py3.9.egg\tortoise\models\autoregressive.py", line 6, in <module>
    import deepspeed
ModuleNotFoundError: No module named 'deepspeed'`

**Comment by houfu** [comment]
The error message suggests your python environment doesn't have the package `deepspeed`.
Check that you have installed all the packages in the `requirements.txt` file by, for example, `pip install -r requirements.txt`

**Comment by starpause** [comment]
I ran into this problem following the readme conda install steps under Windows Power Shell. After trying to get deepspeed installed under Windows I got to a point where it wanted `libaio` to be installed and that's a Linux only tool so I switched over to Ubuntu running in WSL.

Under U/WSL I got further but hit this error:

`assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)"` and had to install the cuda drivers specifically for U/WSL from nvidia (this may have been in the instructions, but I thought since I had the Windows drivers I'd be good): 

https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_network

After that I was finally able to run 

`python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast`

but still get an error trying to run read.py (it's long, pasting below in case anyone has hints or suggestions based on the output).

```
$ python tortoise/read.py --textfile ./text_in/NEARVerse_Constitution_Draft_3.2_\(V1_for_Public\).tts.md --voice lj
[2023-08-01 14:44:31,588] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-01 14:44:31,976] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed info: version=0.10.0, git-hash=unknown, git-branch=unknown
[2023-08-01 14:44:31,978] [WARNING] [config_utils.py:69:_process_deprecated_field] Config parameter mp_size is deprecated use tensor_parallel.tp_size instead
[2023-08-01 14:44:31,978] [INFO] [logging.py:96:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
Using /home/starpause/.cache/torch_extensions/py39_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/starpause/.cache/torch_extensions/py39_cu117/transformer_inference/build.ninja...
Building extension module transformer_inference...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/4] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=transformer_inference -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/includes -I/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include/TH -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/starpause/anaconda3/envs/tortoise/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++17 -c /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/layer_norm.cu -o layer_norm.cuda.o
FAILED: layer_norm.cuda.o
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=transformer_inference -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/includes -I/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include/TH -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/starpause/anaconda3/envs/tortoise/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++17 -c /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/layer_norm.cu -o layer_norm.cuda.o
/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(171): error: no operator "+" matches these operands
            operand types are: const __half + const __half
      return lhs + rhs;
                 ^

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(181): error: no operator ">" matches these operands
            operand types are: const __half > const __half
      return (lhs > rhs) ? lhs : rhs;
                  ^

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(192): error: no operator "<" matches these operands
            operand types are: const __half < const __half
      return (lhs < rhs) ? lhs : rhs;
                  ^

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(200): error: no operator "+" matches these operands
            operand types are: const __half2 + const __half2
      return lhs + rhs;
                 ^

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(210): error: no operator ">" matches these operands
            operand types are: const __half > const __half
      ret_val.x = (lhs.x > rhs.x) ? lhs.x : rhs.x;
                         ^

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(211): error: no operator ">" matches these operands
            operand types are: const __half > const __half
      ret_val.y = (lhs.y > rhs.y) ? lhs.y : rhs.y;
                         ^

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(223): error: no operator "<" matches these operands
            operand types are: const __half < const __half
      ret_val.x = (lhs.x < rhs.x) ? lhs.x : rhs.x;
                         ^

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(224): error: no operator "<" matches these operands
            operand types are: const __half < const __half
      ret_val.y = (lhs.y < rhs.y) ? lhs.y : rhs.y;
                         ^

8 errors detected in the compilation of "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/layer_norm.cu".
[2/4] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=transformer_inference -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/includes -I/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include/TH -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/starpause/anaconda3/envs/tortoise/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++17 -c /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/rms_norm.cu -o rms_norm.cuda.o
FAILED: rms_norm.cuda.o
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=transformer_inference -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/includes -I/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include/TH -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/starpause/anaconda3/envs/tortoise/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++17 -c /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/rms_norm.cu -o rms_norm.cuda.o
/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(171): error: no operator "+" matches these operands
            operand types are: const __half + const __half
      return lhs + rhs;
                 ^

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(181): error: no operator ">" matches these operands
            operand types are: const __half > const __half
      return (lhs > rhs) ? lhs : rhs;
                  ^

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(192): error: no operator "<" matches these operands
            operand types are: const __half < const __half
      return (lhs < rhs) ? lhs : rhs;
                  ^

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(200): error: no operator "+" matches these operands
            operand types are: const __half2 + const __half2
      return lhs + rhs;
                 ^

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(210): error: no operator ">" matches these operands
            operand types are: const __half > const __half
      ret_val.x = (lhs.x > rhs.x) ? lhs.x : rhs.x;
                         ^

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(211): error: no operator ">" matches these operands
            operand types are: const __half > const __half
      ret_val.y = (lhs.y > rhs.y) ? lhs.y : rhs.y;
                         ^

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(223): error: no operator "<" matches these operands
            operand types are: const __half < const __half
      ret_val.x = (lhs.x < rhs.x) ? lhs.x : rhs.x;
                         ^

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(224): error: no operator "<" matches these operands
            operand types are: const __half < const __half
      ret_val.y = (lhs.y < rhs.y) ? lhs.y : rhs.y;
                         ^

8 errors detected in the compilation of "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/rms_norm.cu".
[3/4] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=transformer_inference -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/includes -I/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include/TH -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/starpause/anaconda3/envs/tortoise/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++17 -c /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/gelu.cu -o gelu.cuda.o
FAILED: gelu.cuda.o
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=transformer_inference -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/includes -I/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/includes -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include/TH -isystem /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/starpause/anaconda3/envs/tortoise/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++17 -c /home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/gelu.cu -o gelu.cuda.o
/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/gelu.cu(451): error: no operator "*" matches these operands
            operand types are: __half * __half
              mlp[idx] = mlp[idx] * coef2[idx] + res[idx] * coef1[idx];
                                  ^
          detected during:
            instantiation of "void moe_res_matmul(T *, T *, T *, int, int) [with T=__half]" at line 469
            instantiation of "void launch_moe_res_matmul(T *, T *, T *, int, int, cudaStream_t) [with T=__half]" at line 479

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/gelu.cu(451): error: no operator "*" matches these operands
            operand types are: __half * __half
              mlp[idx] = mlp[idx] * coef2[idx] + res[idx] * coef1[idx];
                                                          ^
          detected during:
            instantiation of "void moe_res_matmul(T *, T *, T *, int, int) [with T=__half]" at line 469
            instantiation of "void launch_moe_res_matmul(T *, T *, T *, int, int, cudaStream_t) [with T=__half]" at line 479

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/gelu.cu(651): error: no operator "+" matches these operands
            operand types are: __half + __half
                  T hidden_state = activation_buffer_1[v] + bias_buffer_1[v];
                                                          ^
          detected during:
            instantiation of "void fused_gate_activation<T,useGelu>(T *, const T *, const T *, int, int, int) [with T=__half, useGelu=true]" at line 695
            instantiation of "void launch_gated_activation(T *, const T *, const T *, int, int, int, __nv_bool, cudaStream_t) [with T=__half]" at line 706

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/gelu.cu(652): error: no operator "+" matches these operands
            operand types are: __half + __half
                  T pre_gate = activation_buffer_2[v] + bias_buffer_2[v];
                                                      ^
          detected during:
            instantiation of "void fused_gate_activation<T,useGelu>(T *, const T *, const T *, int, int, int) [with T=__half, useGelu=true]" at line 695
            instantiation of "void launch_gated_activation(T *, const T *, const T *, int, int, int, __nv_bool, cudaStream_t) [with T=__half]" at line 706

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/gelu.cu(656): error: no operator "*" matches these operands
            operand types are: __half * __half
                  activation_buffer_1[v] = hidden_state * gate;
                                                        ^
          detected during:
            instantiation of "void fused_gate_activation<T,useGelu>(T *, const T *, const T *, int, int, int) [with T=__half, useGelu=true]" at line 695
            instantiation of "void launch_gated_activation(T *, const T *, const T *, int, int, int, __nv_bool, cudaStream_t) [with T=__half]" at line 706

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/gelu.cu(651): error: no operator "+" matches these operands
            operand types are: __half + __half
                  T hidden_state = activation_buffer_1[v] + bias_buffer_1[v];
                                                          ^
          detected during:
            instantiation of "void fused_gate_activation<T,useGelu>(T *, const T *, const T *, int, int, int) [with T=__half, useGelu=false]" at line 698
            instantiation of "void launch_gated_activation(T *, const T *, const T *, int, int, int, __nv_bool, cudaStream_t) [with T=__half]" at line 706

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/gelu.cu(652): error: no operator "+" matches these operands
            operand types are: __half + __half
                  T pre_gate = activation_buffer_2[v] + bias_buffer_2[v];
                                                      ^
          detected during:
            instantiation of "void fused_gate_activation<T,useGelu>(T *, const T *, const T *, int, int, int) [with T=__half, useGelu=false]" at line 698
            instantiation of "void launch_gated_activation(T *, const T *, const T *, int, int, int, __nv_bool, cudaStream_t) [with T=__half]" at line 706

/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/gelu.cu(656): error: no operator "*" matches these operands
            operand types are: __half * __half
                  activation_buffer_1[v] = hidden_state * gate;
                                                        ^
          detected during:
            instantiation of "void fused_gate_activation<T,useGelu>(T *, const T *, const T *, int, int, int) [with T=__half, useGelu=false]" at line 698
            instantiation of "void launch_gated_activation(T *, const T *, const T *, int, int, int, __nv_bool, cudaStream_t) [with T=__half]" at line 706

8 errors detected in the compilation of "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/gelu.cu".
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Users/jorda/Workspace/tortoise-tts/tortoise/read.py", line 33, in <module>
    tts = TextToSpeech(models_dir=args.model_dir, use_deepspeed=args.use_deepspeed, kv_cache=args.kv_cache, half=args.half)
  File "/mnt/c/Users/jorda/Workspace/tortoise-tts/tortoise/api.py", line 231, in __init__
    self.autoregressive.post_init_gpt2_config(use_deepspeed=use_deepspeed, kv_cache=kv_cache, half=self.half)
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/TorToiSe-2.6.0-py3.9.egg/tortoise/models/autoregressive.py", line 375, in post_init_gpt2_config
    self.ds_engine = deepspeed.init_inference(model=self.inference_model,
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/__init__.py", line 342, in init_inference
    engine = InferenceEngine(model, config=ds_inference_config)
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/inference/engine.py", line 192, in __init__
    self._apply_injection_policy(config)
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/inference/engine.py", line 426, in _apply_injection_policy
    replace_transformer_layer(client_module, self.module, checkpoint, config, self.config)
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 523, in replace_transformer_layer
    replaced_module = replace_module(model=model,
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 766, in replace_module
    replaced_module, _ = _replace_module(model, policy, state_dict=sd)
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 847, in _replace_module
    _, layer_id = _replace_module(child,
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 847, in _replace_module
    _, layer_id = _replace_module(child,
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 823, in _replace_module
    replaced_module = policies[child.__class__][0](child,
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 500, in replace_fn
    new_module = replace_with_policy(child,
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 348, in replace_with_policy
    _container.create_module()
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/module_inject/containers/gpt2.py", line 20, in create_module
    self.module = DeepSpeedGPTInference(_config, mp_group=self.mp_group)
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/model_implementations/transformers/ds_gpt.py", line 20, in __init__
    super().__init__(config, mp_group, quantize_scales, quantize_groups, merge_count, mlp_extra_grouping)
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/model_implementations/transformers/ds_transformer.py", line 58, in __init__
    inference_module = builder.load()
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 454, in load
    return self.jit_load(verbose)
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 497, in jit_load
    op_module = load(name=self.name,
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/starpause/anaconda3/envs/tortoise/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'transformer_inference'
```

**Comment by manmay-nakhashi** [comment]
Do export CUDA_HOME="Your cuda directory path" in ubuntu it is usually in /usr/local
