### ISSUE TITLE
ValueError when running CLI script do_tts.py

### ISSUE THREAD

**Issue by V-Cooper** [neonbjb/tortoise-tts#515]
When running script `python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast` in the CLI. 

I receive an error:
```
Traceback (most recent call last):
  File "/content/tortoise-tts/tortoise/do_tts.py", line 7, in <module>
    from api import TextToSpeech, MODELS_DIR
  File "/content/tortoise-tts/tortoise/api.py", line 24, in <module>
    from tortoise.utils.tokenizer import VoiceBpeTokenizer
  File "/usr/local/lib/python3.10/dist-packages/TorToiSe-2.4.2-py3.10.egg/tortoise/utils/tokenizer.py", line 4, in <module>
    import inflect
  File "/usr/local/lib/python3.10/dist-packages/inflect/__init__.py", line 2054, in <module>
    class engine:
  File "/usr/local/lib/python3.10/dist-packages/inflect/__init__.py", line 3791, in engine
    def number_to_words(  # noqa: C901
  File "pydantic/decorator.py", line 36, in pydantic.decorator.validate_arguments.validate
    import re
  File "pydantic/decorator.py", line 126, in pydantic.decorator.ValidatedFunction.__init__
    self.dict = func.__dict__.copy()
  File "pydantic/decorator.py", line 259, in pydantic.decorator.ValidatedFunction.create_model
    """decorator(caller) converts a caller function into a decorator"""
  File "pydantic/main.py", line 972, in pydantic.main.create_model
  File "pydantic/main.py", line 204, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 488, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 534, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 633, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 776, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 451, in pydantic.fields.ModelField._get_field_info
ValueError: `Field` default cannot be set in `Annotated` for 'num_Annotated[str, FieldInfo(min_length=1, extra={})]'
```

**Comment by V-Cooper** [comment]
The problem was resolved by reinstalling pydantic version 1.9.1. 
`pip install pydantic==1.9.1`
