### ISSUE TITLE
python setup.py egg_info while running python -m pip install -r ./requirements.txt 

### ISSUE THREAD

**Issue by jxggx** [neonbjb/tortoise-tts#522]
i was installing tortoise-tts for the first time. when I ran `python -m pip install -r ./requirements.txt`. i got this error. i am new to it, so I have no idea how to solve it.

``` Collecting deepspeed==0.8.3 (from -r ./requirements.txt (line 21))
  Using cached deepspeed-0.8.3.tar.gz (765 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      test.c
      LINK : fatal error LNK1181: cannot open input file 'aio.lib'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Beats\AppData\Local\Temp\pip-install-cqsv16w_\deepspeed_7a5cb21ed0a44e34834606a31dfadaa2\setup.py", line 156, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\Beats\AppData\Local\Temp\pip-install-cqsv16w_\deepspeed_7a5cb21ed0a44e34834606a31dfadaa2\setup.py", line 48, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  One can disable async_io with DS_BUILD_AIO=0
       [ERROR]  Unable to pre-compile async_io
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by manmay-nakhashi** [comment]
@jxggx you can remove deepspeed from a requirements.txt and use the repo ,  i don't use windows so i don't know how to solve it , may be from a community someone will able to solve it.
note:
```
DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  One can disable async_io with DS_BUILD_AIO=0
  ```
you can look at this warnings and see if DS_BUILD_AIO=0 works.

**Comment by micky2be** [comment]
Just so you know, if you wanna use `deepspeed` on Windows:
https://github.com/microsoft/DeepSpeed#windows
