### ISSUE TITLE
I always seem to return this error message.. No module named 'tortouse.models'  Has anyone else run into this?

### ISSUE THREAD

**Issue by Russellva** [neonbjb/tortoise-tts#524]
I'm trying to execute a line a code that will convert text, which I input, into audio format using a clone of my voice. There is a 10 minute long .wav file in the directory listed "Reece_1", which is respectively labelled "Reece_1.wav"

(base) reecethompson@w134-87-147-065 tortoise-tts % caffeinate python tortoise/do_tts.py --text “I must not fear. Fear is the mind-killer. Fear is the little-death that brings total obliteration. I will face my fear. I will permit it to pass over me and through me. And when it has gone past I will turn the inner eye to see its path. Where the fear has gone there will be nothing. Only I will remain.” --voice Reece_1 --preset fast

Traceback (most recent call last):
  File "/Users/reecethompson/tortoise-tts/tortoise-tts/tortoise/do_tts.py", line 7, in <module>
    from api import TextToSpeech, MODELS_DIR
  File "/Users/reecethompson/tortoise-tts/tortoise-tts/tortoise/api.py", line 12, in <module>
    from tortoise.models.classifier import AudioMiniEncoderWithClassifierHead
ModuleNotFoundError: No module named 'tortoise.models'

I always seem to get the same response. "No module named 'tortouse.models'"

I've tried uninstalling, and reinstalling several times. I always seem to get the same return. 

Has anyone ever had this issue before? 
Does anyone have any input on this?

Any help is greatly appreciated!

**Comment by xinwolfthorn** [comment]
i have this exact same issue, any luck fixing it?
