### ISSUE TITLE
Couldn't run tortoise/do_tts.py

### ISSUE THREAD

**Issue by Razor-blip** [neonbjb/tortoise-tts#558]
When I run this script like this: python tortoise/do_tts.py --text "Hello world! I am Benedikt Canmberbatch!" --voice Cillian_Murphy
It gives me this error:
Traceback (most recent call last):
  File "/content/tortoise-tts/tortoise/do_tts.py", line 39, in <module>
    gen, dbg_state = tts.tts_with_preset(args.text, k=args.candidates, voice_samples=voice_samples, conditioning_latents=conditioning_latents,
  File "/content/tortoise-tts/tortoise/api.py", line 333, in tts_with_preset
    return self.tts(text, **settings)
  File "/content/tortoise-tts/tortoise/api.py", line 396, in tts
    auto_conditioning, diffusion_conditioning, auto_conds, _ = self.get_conditioning_latents(voice_samples, return_mels=True)
  File "/content/tortoise-tts/tortoise/api.py", line 279, in get_conditioning_latents
    auto_conds = torch.stack(auto_conds, dim=1)
RuntimeError: stack expects a non-empty TensorList

**Comment by Razor-blip** [comment]
This error also refers to tortoise/read.py

**Comment by Razor-blip** [comment]
I fixed, my voice folder was empty, and thats way TensorList was empty :)
