### ISSUE TITLE
Bug, 

### ISSUE THREAD

**Issue by Gazgiza** [neonbjb/tortoise-tts#568]
"(base) PS C:\Users\gazgiza\tortoise-tts> python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast
C:\Users\youri\anaconda3\Lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
Traceback (most recent call last):
  File "C:\Users\gazgiza\tortoise-tts\tortoise\do_tts.py", line 7, in <module>
    from api import TextToSpeech, MODELS_DIR
  File "C:\Users\gazgiza\tortoise-tts\tortoise\api.py", line 9, in <module>
    import progressbar
ModuleNotFoundError: No module named 'progressbar'  "

I have this issue when I try to generate a speech. I don't know how to fix that.

**Comment by manmay-nakhashi** [comment]
pip install progressbar

**Comment by Gazgiza** [comment]
Now it says 
(base) PS C:\Users\youri> cd tortoise-tts
(base) PS C:\Users\youri\tortoise-tts> python tortoise/do_tts.py --text "[I'm feeling happy] Looking for cheap Steam points, Steam reviews or cs:go accounts with veteran badges? Boosting service . cloud can help you to get them and save your money! Instant delivery, secure payments and a rating of over four and a half stars on Trustpilot.  Problems with your order? Help is always available. Don't wait any longer, this is what you need." --voice aeru --preset standard
C:\Users\youri\anaconda3\Lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
Traceback (most recent call last):
  File "C:\Users\youri\tortoise-tts\tortoise\do_tts.py", line 7, in <module>
    from api import TextToSpeech, MODELS_DIR
  File "C:\Users\youri\tortoise-tts\tortoise\api.py", line 12, in <module>
    from tortoise.models.classifier import AudioMiniEncoderWithClassifierHead
ModuleNotFoundError: No module named 'tortoise'
(base) PS C:\Users\youri\tortoise-tts> pip install tortoise
Collecting tortoise
  Downloading tortoise-0.1.1-py3-none-any.whl (5.3 kB)
Collecting atlastk (from tortoise)
  Downloading atlastk-0.13.2-py3-none-any.whl (24 kB)
Installing collected packages: atlastk, tortoise
Successfully installed atlastk-0.13.2 tortoise-0.1.1
(base) PS C:\Users\youri\tortoise-tts> python tortoise/do_tts.py --text "[I'm feeling happy] Looking for cheap Steam points, Steam reviews or cs:go accounts with veteran badges? Boosting service . cloud can help you to get them and save your money! Instant delivery, secure payments and a rating of over four and a half stars on Trustpilot.  Problems with your order? Help is always available. Don't wait any longer, this is what you need." --voice aeru --preset standard
C:\Users\youri\anaconda3\Lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
Traceback (most recent call last):
  File "C:\Users\youri\tortoise-tts\tortoise\do_tts.py", line 7, in <module>
    from api import TextToSpeech, MODELS_DIR
  File "C:\Users\youri\tortoise-tts\tortoise\api.py", line 12, in <module>
    from tortoise.models.classifier import AudioMiniEncoderWithClassifierHead
ModuleNotFoundError: No module named 'tortoise.models'
(base) PS C:\Users\youri\tortoise-tts> pip install tortoise.models
ERROR: Could not find a version that satisfies the requirement tortoise.models (from versions: none)
ERROR: No matching distribution found for tortoise.models
(base) PS C:\Users\youri\tortoise-tts>

**Comment by manmay-nakhashi** [comment]
pip install -e .

**Comment by Gazgiza** [comment]
Thanks, but I have this error now : OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
