### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by MMoneer** [neonbjb/tortoise-tts#572]
Hello,
I get failed reading error, I add print to the code and I get that :
*******************************************
<_io.BufferedReader name='C:\\Users\\Main/.cache\\huggingface\\hub\\models--jbetker--wav2vec2-large-robust-ft-libritts-voxpopuli\\snapshots\\33e5835aad1c32ac8707971141b65c3fc5ff1904\\pytorch_model.bin'>
*******************************************
*******************************************
<_io.BufferedReader name='C:\\Users\\Main\\.cache\\tortoise\\models\\autoregressive.pth'>
*******************************************
Traceback (most recent call last):
  File "D:\tortoise-tts\tortoise\do_tts.py", line 31, in <module>
    tts = TextToSpeech(models_dir=args.model_dir, use_deepspeed=args.use_deepspeed, kv_cache=args.kv_cache, half=args.half)
  File "D:\tortoise-tts\tortoise\api.py", line 242, in __init__
    self.autoregressive.load_state_dict(torch.load(get_model_path('autoregressive.pth', models_dir)), strict=False)
  File "C:\Users\Main\anaconda3\envs\tortoise\lib\site-packages\torch\serialization.py", line 800, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\Main\anaconda3\envs\tortoise\lib\site-packages\torch\serialization.py", line 286, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

why does it read from the cache folder?

**Comment by MMoneer** [comment]
Hello,
Finally, the issue is solved, For anyone facing the same issue:
1- Go to "C:\Users\(change to your username)\.cache\tortoise\models" delete models in this folder
2- Go to "https://huggingface.co/jbetker/tortoise-tts-v2/tree/main/.models" download models from this url
3- Put the models you downloaded in this folder  "C:\Users\(change to your username)\.cache\tortoise\models"
Good luck

**Comment by romaklym** [comment]
@MMoneer thanks Mohamed, that worked for me as well!
