### ISSUE TITLE
do_tty.py gives CUFF error

### ISSUE THREAD

**Issue by iplayfast** [neonbjb/tortoise-tts#588]
python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast

seems to work, but specifying the voice doesn't. 

python tortoise/do_tts.py --text "I'm going to speak this" --voice train_atkins --preset fast
Traceback (most recent call last):
  File "/home/chris/ai/voice/tortoise-tts/tortoise/do_tts.py", line 41, in <module>
    gen, dbg_state = tts.tts_with_preset(args.text, k=args.candidates, voice_samples=voice_samples, conditioning_latents=conditioning_latents,
  File "/home/chris/ai/voice/tortoise-tts/tortoise/api.py", line 346, in tts_with_preset
    return self.tts(text, **settings)
  File "/home/chris/ai/voice/tortoise-tts/tortoise/api.py", line 409, in tts
    auto_conditioning, diffusion_conditioning, auto_conds, _ = self.get_conditioning_latents(voice_samples, return_mels=True)
  File "/home/chris/ai/voice/tortoise-tts/tortoise/api.py", line 291, in get_conditioning_latents
    auto_conds.append(format_conditioning(vs, device=self.device))
  File "/home/chris/ai/voice/tortoise-tts/tortoise/api.py", line 113, in format_conditioning
    mel_clip = TorchMelSpectrogram()(clip.unsqueeze(0)).squeeze(0)
  File "/home/chris/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chris/.local/lib/python3.10/site-packages/tortoise/models/arch_util.py", line 325, in forward
    mel = self.mel_stft(inp)
  File "/home/chris/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chris/.local/lib/python3.10/site-packages/torchaudio/transforms/_transforms.py", line 642, in forward
    specgram = self.spectrogram(waveform)
  File "/home/chris/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chris/.local/lib/python3.10/site-packages/torchaudio/transforms/_transforms.py", line 108, in forward
    return F.spectrogram(
  File "/home/chris/.local/lib/python3.10/site-packages/torchaudio/functional/functional.py", line 121, in spectrogram
    spec_f = torch.stft(
  File "/home/chris/.local/lib/python3.10/site-packages/torch/functional.py", line 632, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR

**Comment by Untitled47** [comment]
It seems that this issus is related to cuda-11.7, I am good with 11.8 and corresponding pytorch

**Comment by yoyo115956** [comment]
> It seems that this issus is related to cuda-11.7, I am good with 11.8 and corresponding pytorch

Definitely addressed my problem, thank u!!!
