### ISSUE TITLE
Deepspeed not in setup.py

### ISSUE THREAD

**Issue by darkphyre** [neonbjb/tortoise-tts#608]
I'm unable to get deepspeed to work with miniconda, part of the reason I found is that the setup.py does not have deepspeed in the install requires.  A second part is, if you add it, you get the following error:

, line 41, in installed_cuda_version
          assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)"
      AssertionError: CUDA_HOME does not exist, unable to compile CUDA op(s)

`install_requires=[
        'tqdm',
        'rotary_embedding_torch',
        'inflect',
        'progressbar',
        'einops',
        'unidecode',
        'scipy',
        'librosa',
        'transformers==4.31.0',
        'deepspeed==0.8.3',
        'tokenizers',
    ],`

**Comment by darkphyre** [comment]
If you try to use deepspeed you get ModuleNotFoundError: No module named 'deepspeed'

**Comment by manmay-nakhashi** [comment]
Done

**Comment by darkphyre** [comment]
So i found this post after I posted (of course): https://github.com/neonbjb/tortoise-tts/issues/556

So i installed the cuda driver for my OS and restarted, now I am getting 


`      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\CallMeRed\AppData\Local\Temp\pip-install-68p_b2q8\deepspeed_0352dda8ffec45288103481191a6b648\setup.py", line 182, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\CallMeRed\AppData\Local\Temp\pip-install-68p_b2q8\deepspeed_0352dda8ffec45288103481191a6b648\setup.py", line 52, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      DS_BUILD_OPS=1
      ←[93m [WARNING] ←[0m async_io requires the dev libaio .so object and headers but these were not found.
      ←[93m [WARNING] ←[0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
      ←[93m [WARNING] ←[0m One can disable async_io with DS_BUILD_AIO=0
      ←[31m [ERROR] ←[0m Unable to pre-compile async_io`


So I learned about the windows fix set DS_BUILD_AIO=0
and then tried pip install deepspeed=.0.8.3 but that fails, so i fixed the transformers pip install transformers==4.31.0
and the next issue is: 

` DeepSpeed Op Builder: Installed CUDA version 12.2 does not match the version torch was compiled with 11.7, unable to compile cuda/cpp extensions without a matching cuda version.
      DS_BUILD_OPS=1
      ←[93m [WARNING] ←[0m async_io requires the dev libaio .so object and headers but these were not found.
      ←[93m [WARNING] ←[0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.`

This is a rabbit hole..

**Comment by darkphyre** [comment]
https://github.com/microsoft/DeepSpeed/blob/master/build_win.bat

**Comment by darkphyre** [comment]
@manmay-nakhashi maybe there is a reason it's not there by default, you have to install the nvidia cuda drivers, and then you have 2 more peoples which I don't know how to work around.  1 is you need to run the following

set DS_BUILD_AIO=0
pip install transformers==4.31.0
pip install deepspeed=.0.8.3

but now i'm stuck here...

`line 105, in assert_no_cuda_mismatch
          raise Exception(
      Exception: >- DeepSpeed Op Builder: Installed CUDA version 12.2 does not match the version torch was compiled with 11.7, unable to compile cuda/cpp extensions without a matching cuda version.
      DS_BUILD_OPS=1`

**Comment by darkphyre** [comment]
Based on the last comment here: https://github.com/microsoft/DeepSpeed/issues/3223 you can use set DS_SKIP_CUDA_CHECK=1
and then pip install deepspeeed, however that's not going to work

`(tortoise) M:\tortoisetts\tortoise-tts>python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast --use_deepspeed true
Traceback (most recent call last):
  File "M:\tortoisetts\tortoise-tts\tortoise\do_tts.py", line 31, in <module>
    tts = TextToSpeech(models_dir=args.model_dir, use_deepspeed=args.use_deepspeed, kv_cache=args.kv_cache, half=args.half)
  File "M:\tortoisetts\tortoise-tts\tortoise\api.py", line 248, in __init__
    self.autoregressive.post_init_gpt2_config(use_deepspeed=use_deepspeed, kv_cache=kv_cache, half=self.half)
  File "C:\minconda\envs\tortoise\lib\site-packages\tortoise-2.8.0-py3.9.egg\tortoise\models\autoregressive.py", line 379, in post_init_gpt2_config
    import deepspeed
  File "C:\minconda\envs\tortoise\lib\site-packages\deepspeed\__init__.py", line 9, in <module>
    from .runtime.engine import DeepSpeedEngine
  File "C:\minconda\envs\tortoise\lib\site-packages\deepspeed\runtime\engine.py", line 12, in <module>
    from tensorboardX import SummaryWriter
  File "C:\minconda\envs\tortoise\lib\site-packages\tensorboardX\__init__.py", line 5, in <module>
    from .torchvis import TorchVis
  File "C:\minconda\envs\tortoise\lib\site-packages\tensorboardX\torchvis.py", line 11, in <module>
    from .writer import SummaryWriter
  File "C:\minconda\envs\tortoise\lib\site-packages\tensorboardX\writer.py", line 15, in <module>
    from .event_file_writer import EventFileWriter
  File "C:\minconda\envs\tortoise\lib\site-packages\tensorboardX\event_file_writer.py", line 28, in <module>
    from .proto import event_pb2
  File "C:\minconda\envs\tortoise\lib\site-packages\tensorboardX\proto\event_pb2.py", line 15, in <module>
    from tensorboardX.proto import summary_pb2 as tensorboardX_dot_proto_dot_summary__pb2
  File "C:\minconda\envs\tortoise\lib\site-packages\tensorboardX\proto\summary_pb2.py", line 15, in <module>
    from tensorboardX.proto import tensor_pb2 as tensorboardX_dot_proto_dot_tensor__pb2
  File "C:\minconda\envs\tortoise\lib\site-packages\tensorboardX\proto\tensor_pb2.py", line 15, in <module>
    from tensorboardX.proto import resource_handle_pb2 as tensorboardX_dot_proto_dot_resource__handle__pb2
  File "C:\minconda\envs\tortoise\lib\site-packages\tensorboardX\proto\resource_handle_pb2.py", line 35, in <module>
    _descriptor.FieldDescriptor(
  File "C:\minconda\envs\tortoise\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates`

**Comment by darkphyre** [comment]
@manmay-nakhashi okay the whole issue might be that the cuda link is the post above goes to 12.2, I am going to try and uninstall 12.2 and install 11.7
https://github.com/neonbjb/tortoise-tts/issues/556#issuecomment-1670292892

https://developer.nvidia.com/cuda-11-7-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exe_local

**Comment by junwang4** [comment]
> I am going to try and uninstall 12.2 and install 11.7

Does CUDA-11.7 work for deepspeed? (I am using ver 12.1, which doesn't work for deepspeed)

**Comment by CodeHeroJo** [comment]
So what's the fix eventually? When I do this set DS_BUILD_AIO=0
pip install transformers==4.31.0
pip install deepspeed==0.8.3
it still says
 [ERROR]  Unable to pre-compile sparse_attn
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by manmay-nakhashi** [comment]
Because of too many errors in deepspeed I have removed it by default in the latest release.

**Comment by GUUser91** [comment]
I found the solution for the windows and linux version.
Here is the windows solution
https://www.youtube.com/watch?v=RVzpjYOV-Tk

linux solution. follow the instruction from this link. This also works with CUDA 12.2
https://github.com/microsoft/DeepSpeed/issues/2902#issuecomment-1530051657
> Remove the restriction on CUDA major version matching in DeepSpeed. You can do that by cloning the DeepSpeed Repo and modifying op_builder/builder.py to remove the exception. Then install DeepSpeed from source with pip install . in the cloned repo.
