### ISSUE TITLE
error installing deepseed from requirements

### ISSUE THREAD

**Issue by Sinicyn78** [neonbjb/tortoise-tts#609]
WIN 11
13700
32
anaconda

Collecting deepspeed==0.8.3 (from -r requirements.txt (line 19))
  Using cached deepspeed-0.8.3.tar.gz (765 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Temp\pip-install-kkpsxi0o\deepspeed_90d26b185c5a4f14937b4ae86201acac\setup.py", line 78, in <module>
          cupy = f"cupy-cuda{''.join(map(str,installed_cuda_version()))}"
        File "C:\Temp\pip-install-kkpsxi0o\deepspeed_90d26b185c5a4f14937b4ae86201acac\op_builder\builder.py", line 46, in installed_cuda_version
          output = subprocess.check_output([cuda_home + "/bin/nvcc",
        File "C:\Users\sinic\anaconda3\envs\tortoise\lib\subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\sinic\anaconda3\envs\tortoise\lib\subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\sinic\anaconda3\envs\tortoise\lib\subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\sinic\anaconda3\envs\tortoise\lib\subprocess.py", line 1436, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] Не удается найти указанный файл
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by darkphyre** [comment]
So this might be from a change I posted earlier and deepspeed was added to the requirements file.

The problem is you need to make sure you download cuda 11.7 driver https://developer.nvidia.com/cuda-11-7-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exe_local

Like, make sure you get the exact 11.7 driver, but even after that I am now running into:


` Using cached deepspeed-0.8.3.tar.gz (765 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\CallMeRed\AppData\Local\Temp\pip-install-0hsn19a7\deepspeed_911510a3fdf342e8b834ae4e0e5dc915\setup.py", line 78, in <module>
          cupy = f"cupy-cuda{''.join(map(str,installed_cuda_version()))}"
        File "C:\Users\CallMeRed\AppData\Local\Temp\pip-install-0hsn19a7\deepspeed_911510a3fdf342e8b834ae4e0e5dc915\op_builder\builder.py", line 46, in installed_cuda_version
          output = subprocess.check_output([cuda_home + "/bin/nvcc",
        File "C:\miniconda3\envs\tortoise\lib\subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\miniconda3\envs\tortoise\lib\subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\miniconda3\envs\tortoise\lib\subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\miniconda3\envs\tortoise\lib\subprocess.py", line 1436, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.`

**Comment by darkphyre** [comment]
Yeah even when using the setup.py

`Running deepspeed-0.8.3\setup.py -q bdist_egg --dist-dir C:\Users\CALLME~1\AppData\Local\Temp\easy_install-njz3njn8\deepspeed-0.8.3\egg-dist-tmp-_hdc5upi
error: [WinError 2] The system cannot find the file specified`

**Comment by darkphyre** [comment]
Basically if you want a quick way aroud it, remove the deepspeed from the setup.py

**Comment by arsen3d** [comment]
Solution: set default to false on line 17 in do_tts.py
```
    parser.add_argument('--use_deepspeed', type=bool, help='Use deepspeed for speed bump.', default=False)
```
