### ISSUE TITLE
Despite following installation requirements to the letter, installation encounters error and aborts.

### ISSUE THREAD

**Issue by Cappan** [neonbjb/tortoise-tts#629]
I'm going to get ahead of things by saying that this is almost certainly the result of me failing to do something that is typically so obvious that whoever wrote the Conda installation guide would not think to mention it, so before I get called inexperienced or otherwise clowned on: I know. It also warrants disclosing that I am running Windows 10, and contrary to what the error log says, CUDA is very much installed.

I've got some kind of error related to DeepSpeed I'm running into when trying to install setup.py as per the instructions. Here's the result I get from running python `setup.py install`:

Installed c:\users\MYNAME\.conda\envs\tortoise\lib\site-packages\tortoise-2.8.0-py3.9.egg
Processing dependencies for TorToiSe==2.8.0
Searching for deepspeed==0.8.3
Reading https://pypi.org/simple/deepspeed/
Downloading https://files.pythonhosted.org/packages/0f/c0/9b57e9ec56f6f405726a384b109f8da1267e41feea081850c2fce1735712/deepspeed-0.8.3.tar.gz#sha256=68f6270ddd90be387c56512a7bc24d61bf36b339e009f493b556a7cbba2522fb
Best match: deepspeed 0.8.3
Processing deepspeed-0.8.3.tar.gz
Writing C:\Users\MYNAME\AppData\Local\Temp\easy_install-0jwg951b\deepspeed-0.8.3\setup.cfg
Running deepspeed-0.8.3\setup.py -q bdist_egg --dist-dir C:\Users\MYNAME\AppData\Local\Temp\easy_install-0jwg951b\deepspeed-0.8.3\egg-dist-tmp-2q8hllqy
No CUDA runtime is found, using CUDA_HOME='C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA\v11.7'
[WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
DS_BUILD_OPS=1
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  One can disable async_io with DS_BUILD_AIO=0
 [ERROR]  Unable to pre-compile async_io
Traceback (most recent call last):
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\sandbox.py", line 156, in save_modules
    yield saved
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "C:\Users\MYNAME\AppData\Local\Temp\easy_install-0jwg951b\deepspeed-0.8.3\setup.py", line 156, in <module>
  File "C:\Users\MYNAME\AppData\Local\Temp\easy_install-0jwg951b\deepspeed-0.8.3\setup.py", line 48, in abort
AssertionError: Unable to pre-compile async_io

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Tortoise\tortoise-tts-main\setup.py", line 6, in <module>
    setuptools.setup(
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\command\install.py", line 80, in run
    self.do_egg_install()
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\command\install.py", line 137, in do_egg_install
    cmd.run(show_deprecation=False)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\command\easy_install.py", line 416, in run
    self.easy_install(spec, not self.no_deps)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\command\easy_install.py", line 658, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
    self.process_distribution(spec, dist, deps)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\command\easy_install.py", line 750, in process_distribution
    distros = WorkingSet([]).resolve(
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\pkg_resources\__init__.py", line 829, in resolve
    dist = self._resolve_dist(
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\pkg_resources\__init__.py", line 865, in _resolve_dist
    dist = best[req.key] = env.best_match(
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\pkg_resources\__init__.py", line 1135, in best_match
    return self.obtain(req, installer)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\pkg_resources\__init__.py", line 1147, in obtain
    return installer(requirement)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\command\easy_install.py", line 677, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\command\easy_install.py", line 703, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\command\easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\command\easy_install.py", line 1170, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\command\easy_install.py", line 1154, in run_setup
    run_setup(setup_script, args)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\sandbox.py", line 262, in run_setup
    raise
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\sandbox.py", line 156, in save_modules
    yield saved
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "C:\Users\MYNAME\.conda\envs\tortoise\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "C:\Users\MYNAME\AppData\Local\Temp\easy_install-0jwg951b\deepspeed-0.8.3\setup.py", line 156, in <module>
  File "C:\Users\MYNAME\AppData\Local\Temp\easy_install-0jwg951b\deepspeed-0.8.3\setup.py", line 48, in abort
AssertionError: Unable to pre-compile async_io

Please help, I'm sick of having to rely on web-based TTS tools, and want to be silly from the comfort of my own machine.

**Comment by esvoaca** [comment]
Yeah it has something to do with deepspeed and not being able to install it on windows.

You can try to go the Docker route meanwhile, I managed to install it that way and got it to work with the CPU at least (didn't try GPU)
