### ISSUE TITLE
Cannot find tortoise.models

### ISSUE THREAD

**Issue by JoTheStupid** [neonbjb/tortoise-tts#652]
when i try anything it tells me "
Traceback (most recent call last):
  File "C:\Users\perri\tortoise-tts\tortoise\do_tts.py", line 7, in <module>
    from api import TextToSpeech, MODELS_DIR
  File "C:\Users\perri\tortoise-tts\tortoise\api.py", line 12, in <module>
    from tortoise.models.classifier import AudioMiniEncoderWithClassifierHead
ModuleNotFoundError: No module named 'tortoise.models'
"
How do i fix this 😭

**Comment by manmay-nakhashi** [comment]
You need to set env variable PYTHONPATH or do pip install -e . , or do python3 setup.py install.

**Comment by JoTheStupid** [comment]
Now its saying ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' (C:\Users\NAME\anaconda3\envs\tortoise-tts\lib\site-packages\charset_normalizer\constant.py)
