### ISSUE TITLE
do_tts.py failing to create result file

### ISSUE THREAD

**Issue by kingsumos** [neonbjb/tortoise-tts#659]
Hi,

Here tortchaudio ffmpeg backend is failling to create the result file, what is the recommended version?

`(tortoise) root@8edf52e791a5:~/tortoise-tts# python tortoise/do_tts.py --candidates 1 --text "hello world" --voice random --preset fast
Generating autoregressive samples..
100%|█████████████████████████████████████████████████████████████████████████████████| 6/6 [00:16<00:00,  2.81s/it]
Computing best candidates using CLVP
100%|█████████████████████████████████████████████████████████████████████████████████| 6/6 [00:04<00:00,  1.29it/s]
Transforming autoregressive outputs into audio..
100%|███████████████████████████████████████████████████████████████████████████████| 80/80 [00:08<00:00,  9.74it/s]
Traceback (most recent call last):
  File "tortoise/do_tts.py", line 47, in <module>
    torchaudio.save(os.path.join(args.output_path, f'{selected_voice}_{k}.wav'), gen.squeeze(0).cpu(), 24000)
  File "/root/audio/src/torchaudio/_backend/utils.py", line 313, in save
    return backend.save(
  File "/root/audio/src/torchaudio/_backend/ffmpeg.py", line 316, in save
    save_audio(
  File "/root/audio/src/torchaudio/_backend/ffmpeg.py", line 247, in save_audio
    s = torchaudio.io.StreamWriter(uri, format=muxer, buffer_size=buffer_size)
  File "/root/audio/src/torio/io/_streaming_media_encoder.py", line 199, in __init__
    self._s = ffmpeg_ext.StreamingMediaEncoder(str(dst), format)
RuntimeError: Failed to open output "results/random_0.wav" (Invalid argument).
(tortoise) root@8edf52e791a5:~/tortoise-tts#
`

I have build torchaudio from sources (latest version):

(tortoise) root@8edf52e791a5:~/tortoise-tts# pip list | grep torch
rotary-embedding-torch    0.3.4
torch                     2.1.0a0+41361538.nv23.6
torchaudio                2.2.0a0+6e26515         /root/audio/src

Thanks!

**Comment by kingsumos** [comment]
Could someone kindly advise on the recommended version of the 'torchaudio' package that I should use?
