### ISSUE TITLE
If using any voice except "random" it is lead to error

### ISSUE THREAD

**Issue by UserOnion** [neonbjb/tortoise-tts#675]
Anaconda, VS Code, lattest Tortosie-TTS, 
_if python tortoise/do_tts.py --text "Testing and Testing!" --voice random --preset fast_ == **working fine**

_if python tortoise/do_tts.py --text "Testing and Testing!" --voice **(any voice here from voices)**  --preset fast_ == **error** 

( as the error is big ) end of the error: 

<SNIP>
  _#pragma unroll
        for (int j = 0; j < thread_work_size; j++) {
          out0[j] = abs_kernel<std::complex<float>>(arg0[j] );
        }

        using vec_t_output = aligned_vector<std::complex<float>, vec_size>;
        vec_t_output* to_0 = reinterpret_cast<vec_t_output*>(data[0]) + block_work_size / vec_size * idx;

        int thread_idx = threadIdx.x;
        #pragma unroll
        for (int i = 0; i<loop_size; i++){
          vec_t_output v;
          #pragma unroll
          for (int j=0; j<vec_size; j++){
          v.val[j] = out0[vec_size * i + j];
          }
          to_0[thread_idx] = v;_

          thread_idx += num_threads;
        }
      }
  }
nvrtc: error: failed to open nvrtc-builtins64_121.dll.
  Make sure that nvrtc-builtins64_121.dll is installed correctly.

**Comment by Patrick970Gaming** [comment]
I am also having this issue, im running a gtx 1070ti with cuda 11.7 installed and GeForce driver 537.42.
Im running conda py10_23.10.0.1 and installed the cuda compatible libraries with this command: 
`conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia`

**Comment by neoneye** [comment]
I'm macOS with M1 cpu and is having the same problem. The random voice work. The other voices doesn't work. 

```
(.venv) PROMPT> python do_tts.py --text "I'm going to speak this" --voice emma --preset fast 
Some weights of the model checkpoint at jbetker/wav2vec2-large-robust-ft-libritts-voxpopuli were not used when initializing Wav2Vec2ForCTC: ['wav2vec2.encoder.pos_conv_embed.conv.weight_g', 'wav2vec2.encoder.pos_conv_embed.conv.weight_v']
- This IS expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at jbetker/wav2vec2-large-robust-ft-libritts-voxpopuli and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/long/path/to/.venv/lib/python3.12/site-packages/torch/nn/utils/weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "/long/path/to/tortoise-tts/tortoise/do_tts.py", line 41, in <module>
    gen, dbg_state = tts.tts_with_preset(args.text, k=args.candidates, voice_samples=voice_samples, conditioning_latents=conditioning_latents,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/long/path/to/tortoise-tts/tortoise/api.py", line 328, in tts_with_preset
    return self.tts(text, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/long/path/to/tortoise-tts/tortoise/api.py", line 391, in tts
    auto_conditioning, diffusion_conditioning, auto_conds, _ = self.get_conditioning_latents(voice_samples, return_mels=True)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/long/path/to/tortoise-tts/tortoise/api.py", line 276, in get_conditioning_latents
    self.stft = TacotronSTFT(1024, 256, 1024, 100, 24000, 0, 12000).to(self.device)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/long/path/to/.venv/lib/python3.12/site-packages/tortoise/utils/audio.py", line 149, in __init__
    from librosa.filters import mel as librosa_mel_fn
  File "/long/path/to/.venv/lib/python3.12/site-packages/librosa/filters.py", line 59, in <module>
    from .core.convert import note_to_hz, hz_to_midi, midi_to_hz, hz_to_octs
  File "/long/path/to/.venv/lib/python3.12/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/long/path/to/.venv/lib/python3.12/site-packages/librosa/core/notation.py", line 8, in <module>
    from .intervals import INTERVALS
  File "/long/path/to/.venv/lib/python3.12/site-packages/librosa/core/intervals.py", line 8, in <module>
    from pkg_resources import resource_filename
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by DanBelo** [comment]
same here
only 'random' option works
if i specify a voice it lead to erro
 in get_conditioning_latents
    cond_mel = wav_to_univnet_mel(sample.to(self.device), do_normalization=False,
TypeError: wav_to_univnet_mel() got an unexpected keyword argument 'stft'

**Comment by appatalks** [comment]
> solved it by removing the stft=self.stft parameter from wav_to_univnet_mel call on api.py

This worked for me as well.
