### ISSUE TITLE
Weird Torch behaviour in WSL2 after autoregressive samples

### ISSUE THREAD

**Issue by Benjy355** [neonbjb/tortoise-tts#691]
I'm pretty sure this isn't tortoise-tts' problem but I figured I would make a post just in case someone who knows more. I'm pretty green on any of these libraries. :(
I'm finding in WSL that, although my GPU has plenty of VRAM left, PyTorch is losing it's shit after the autoregressive samples are done. If you see in the CUDA out of memory error, it claims that 4.26GiB is free, but somehow the process is using ... 17179869184 GiB? 😅 Any advice, or where I can look/research/troubleshoot would be greatly appreciated. I haven't been able to find info on pyTorch stating it's using some random/absurd amount of memory
Below is the CMD line from a test.
```
>python3 do_tts.py --text "Test" --voice random --preset fast
Some weights of the model checkpoint at jbetker/wav2vec2-large-robust-ft-libritts-voxpopuli were not used when initializing Wav2Vec2ForCTC: ['wav2vec2.encoder.pos_conv_embed.conv.weight_g', 'wav2vec2.encoder.pos_conv_embed.conv.weight_v']
- This IS expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at jbetker/wav2vec2-large-robust-ft-libritts-voxpopuli and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/benjy355/.local/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Generating autoregressive samples..
100%|███████████████████████████████████████████████████████████████████████████████████| 24/24 [00:25<00:00,  1.05s/it]Computing best candidates using CLVP
  0%|                                                                                            | 0/24 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/mnt/c/randomapps/tortoise-tts-venv/tortoise-tts/tortoise/do_tts.py", line 41, in <module>
    gen, dbg_state = tts.tts_with_preset(args.text, k=args.candidates, voice_samples=voice_samples, conditioning_latents=conditioning_latents,
  File "/mnt/c/randomapps/tortoise-tts-venv/tortoise-tts/tortoise/api.py", line 321, in tts_with_preset
    return self.tts(text, **settings)
  File "/mnt/c/randomapps/tortoise-tts-venv/tortoise-tts/tortoise/api.py", line 452, in tts
    clvp_out = clvp(text_tokens.repeat(batch.shape[0], 1), batch, return_loss=False)
  File "/home/benjy355/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl    return self._call_impl(*args, **kwargs)
  File "/home/benjy355/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/benjy355/.local/lib/python3.10/site-packages/tortoise/models/clvp.py", line 121, in forward
    enc_speech = self.speech_transformer(speech_emb, mask=voice_mask)
  File "/home/benjy355/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl    return self._call_impl(*args, **kwargs)
  File "/home/benjy355/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/benjy355/.local/lib/python3.10/site-packages/tortoise/models/arch_util.py", line 370, in forward
    h = self.transformer(x, **kwargs)
  File "/home/benjy355/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl    return self._call_impl(*args, **kwargs)
  File "/home/benjy355/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/benjy355/.local/lib/python3.10/site-packages/tortoise/models/xtransformers.py", line 1233, in forward
    x, intermediates = self.attn_layers(x, mask=mask, mems=mems, return_hiddens=True, **kwargs)
  File "/home/benjy355/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl    return self._call_impl(*args, **kwargs)
  File "/home/benjy355/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/benjy355/.local/lib/python3.10/site-packages/tortoise/models/xtransformers.py", line 968, in forward
    out, inter, k, v = block(x, None, mask, None, attn_mask, self.pia_pos_emb, rotary_pos_emb,
  File "/home/benjy355/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl    return self._call_impl(*args, **kwargs)
  File "/home/benjy355/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/benjy355/.local/lib/python3.10/site-packages/tortoise/models/arch_util.py", line 347, in forward
    return partial(x, *args)
  File "/home/benjy355/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl    return self._call_impl(*args, **kwargs)
  File "/home/benjy355/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/benjy355/.local/lib/python3.10/site-packages/tortoise/models/xtransformers.py", line 705, in forward
    post_softmax_attn = attn.clone()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 46.00 MiB. GPU 0 has a total capacty of 8.00 GiB of which 4.28 GiB is free. Including non-PyTorch memory, this process has 17179869184.00 GiB memory in use. Of the allocated memory 2.60 GiB is allocated by PyTorch, and 24.50 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```

**Comment by JeffPlsFix** [comment]
I had some similar issues on WSL. Would use 99% system memory (32GB) and try to allocate 20+ gigs of vram on my 11 gig GPU, but only when it came to "Computing best candidates using CLVP" after generating autoregressive samples.

### I was using the **tortoise-tts-fastest** fork though.

Had to do a complete reinstall from scratch, wiped WSL and display drivers aswell. 
Afterwards the memory usage was normal.
I wrote a gist with the installation order on WSL which i could use to reproduce a stable installation.

https://gist.github.com/JeffPlsFix/9ff3137a42f6f1f5f8ba1a441eea413c

Unsure if this is any help, but i suggest reinstalling all and watch your package versions. Cant for sure say this repo has the same installation steps as the fork though, but the issue sounds the same.
