### ISSUE TITLE
cvvp.pth no longer in hugging face repo Manmay

### ISSUE THREAD

**Issue by jimbeggs** [neonbjb/tortoise-tts#692]
Just wanted to say thanks for the fine work here. I am working on re-enacting historical events for educational purposes and am trying different hyperparameters in your models to get different emotions etc.  I ran into this problem along the way.

When setting a cvvp value other than 0 I am seeing an error which seems to indicate that Manmay changed location or removed cvvp.pth altogether.

(tortoise) jim@DESKTOP-4LVSK0B:~/dev/tortoise-tts$ python3 tortoise/generate.py --voice angie --text "Hello, my name is
Agnie what is yours?" --candidates 5 --cvvp_amount .5
Generating autoregressive samples..
100%|█████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:08<00:00,  1.44s/it]Traceback (most recent call last):
  File "/opt/conda/envs/tortoise/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/opt/conda/envs/tortoise/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/Manmay/tortoise-tts/resolve/main/cvvp.pth

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jim/dev/tortoise-tts/tortoise/generate.py", line 68, in <module>
    inference(tts=tts, text=args.text, selected_voices=selected_voices, output_path=args.output_path, preset=args.preset, candidates=args.candidates, seed=args.seed, cvvp_amount=args.cvvp_amount, produce_debug_state=args.produce_debug_state)
  File "/home/jim/dev/tortoise-tts/tortoise/generate.py", line 22, in inference
    gen, dbg_state = tts.tts_with_preset(text, k=candidates, voice_samples=voice_samples, conditioning_latents=conditioning_latents,
  File "/home/jim/dev/tortoise-tts/tortoise/api.py", line 321, in tts_with_preset
    return self.tts(text, **settings)
  File "/home/jim/dev/tortoise-tts/tortoise/api.py", line 441, in tts
    self.load_cvvp()
  File "/home/jim/dev/tortoise-tts/tortoise/api.py", line 250, in load_cvvp
    self.cvvp.load_state_dict(torch.load(get_model_path('cvvp.pth', self.models_dir)))
  File "/home/jim/dev/tortoise-tts/tortoise/api.py", line 48, in get_model_path
    model_path = hf_hub_download(repo_id="Manmay/tortoise-tts", filename=model_name, cache_dir=models_dir)
  File "/opt/conda/envs/tortoise/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/tortoise/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1195, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/opt/conda/envs/tortoise/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/tortoise/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1541, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/opt/conda/envs/tortoise/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 269, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-656371ae-70e5851a77f732622b58c491)

Entry Not Found for url: https://huggingface.co/Manmay/tortoise-tts/resolve/main/cvvp.pth.

**Comment by iampraveensingh** [comment]
Entry Not Found for url: https://huggingface.co/Manmay/tortoise-tts/resolve/main/classifier.pth.
this also not available 

![image](https://github.com/neonbjb/tortoise-tts/assets/42860981/f8f415b8-266c-49d1-8e8a-7dddac1e288c)

**Comment by robbintt** [comment]
Same issue here.

**Comment by neonbjb** [comment]
I did some further testing after I released this repo and found that CVVP filtering wasn't actually doing anything. I would not recommend setting this weight to anything other than 0 anyway and the code should probably be removed.

**Comment by jimbeggs** [comment]
Thanks for the feedback appreciate you taking the time to reply!

**Comment by TechnoLukas** [comment]
Hello.
I am just trying to follow this guide https://github.com/neonbjb/tortoise-tts/blob/main/Advanced_Usage.md
And there is a command `python tortoise/is_this_from_tortoise.py --clip=<path_to_suspicious_audio_file>` that gives `Entry Not Found for url: https://huggingface.co/Manmay/tortoise-tts/resolve/main/classifier.pth.
` error.
So I can not follow this guide anymore?
Maybe I misunderstood something.

**Comment by nandaanumolu** [comment]
same issue here classifier path is not available
