### ISSUE TITLE
Don't know what's going on

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [neonbjb/tortoise-tts#717]
Tried to install tortoise-tts but got this error

```
Traceback (most recent call last):
  File "C:\Users\PC2022\tortoise-tts\tortoise\do_tts.py", line 7, in <module>
    from api import TextToSpeech, MODELS_DIR
  File "C:\Users\PC2022\tortoise-tts\tortoise\api.py", line 14, in <module>
    from tortoise.models.autoregressive import UnifiedVoice
  File "C:\Users\PC2022\miniconda3\envs\tortoise\lib\site-packages\tortoise_tts-3.0.0-py3.9.egg\tortoise\models\autoregressive.py", line 6, in <module>
    from transformers import GPT2Config, GPT2PreTrainedModel, LogitsProcessorList
  File "C:\Users\PC2022\miniconda3\envs\tortoise\lib\site-packages\transformers-4.31.0-py3.9.egg\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\Users\PC2022\miniconda3\envs\tortoise\lib\site-packages\transformers-4.31.0-py3.9.egg\transformers\dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\Users\PC2022\miniconda3\envs\tortoise\lib\site-packages\transformers-4.31.0-py3.9.egg\transformers\utils\__init__.py", line 18, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

What does this mean?

**Comment by migueldubme** [comment]
Try pip install packaging, it means that you dont have that library installed
