### ISSUE TITLE
Utilities not found

### ISSUE THREAD

**Issue by eliich** [neonbjb/tortoise-tts#732]
```
C:\Users\USER\Programming\AI\Voice\TortoiseTTS\ai-voice-cloning>runtime\python.exe .\src\main.py
Whisper detected
Traceback (most recent call last):
  File "C:\Users\USER\Programming\AI\Voice\TortoiseTTS\ai-voice-cloning\src\utils.py", line 98, in <module>
    from vall_e.emb.qnt import encode as valle_quantize
ModuleNotFoundError: No module named 'vall_e'

Traceback (most recent call last):
  File "C:\Users\USER\Programming\AI\Voice\TortoiseTTS\ai-voice-cloning\src\utils.py", line 118, in <module>
    import bark
ModuleNotFoundError: No module named 'bark'

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loading Tortoise with Hifigan
C:\Users\USER\Programming\AI\Voice\TortoiseTTS\ai-voice-cloning\runtime\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Loading tokenizer JSON: ./modules/tortoise-tts/tortoise/data/tokenizer.json
Loaded tokenizer
Loading autoregressive model: C:\Users\USER\Programming\AI\Voice\TortoiseTTS\ai-voice-cloning\models\tortoise\autoregressive.pth
[2024-02-19 10:41:24,976] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed info: version=0.8.3+6eca037c, git-hash=6eca037c, git-branch=HEAD
[2024-02-19 10:41:24,977] [WARNING] [config_utils.py:69:_process_deprecated_field] Config parameter mp_size is deprecated use tensor_parallel.tp_size instead
[2024-02-19 10:41:24,977] [INFO] [logging.py:96:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
WARNING! Setting BLOOMLayerPolicy._orig_layer_class to None due to Exception: module 'transformers.models' has no attribute 'bloom'
[2024-02-19 10:41:24,998] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed-Inference config: {'layer_id': 0, 'hidden_size': 1024, 'intermediate_size': 4096, 'heads': 16, 'num_hidden_layers': -1, 'fp16': False, 'pre_layer_norm': True, 'local_rank': -1, 'stochastic_mode': False, 'epsilon': 1e-05, 'mp_size': 1, 'q_int8': False, 'scale_attention': True, 'triangular_masking': True, 'local_attention': False, 'window_size': 1, 'rotary_dim': -1, 'rotate_half': False, 'rotate_every_two': True, 'return_tuple': True, 'mlp_after_attn': True, 'mlp_act_func_type': <ActivationFuncType.GELU: 1>, 'specialized_mode': False, 'training_mp_size': 1, 'bigscience_bloom': False, 'max_out_tokens': 1024, 'scale_attn_by_inverse_layer_idx': False, 'enable_qkv_quantization': False, 'use_mup': False, 'return_single_tuple': False}
Loaded autoregressive model
Loaded TTS, ready for generation.
```

**Comment by eliich** [comment]
To summarize 
```
ModuleNotFoundError: No module named 'bark'
```
and
```
ModuleNotFoundError: No module named 'vall_e'
```

**Comment by dhamaraiselvi** [comment]
pip install bark

**Comment by dhamaraiselvi** [comment]
pip install bark
pip install git+https://github.com/korakoe/VALL-E-X.git
