### ISSUE TITLE
ModuleNotFoundError: No module named 'beartype'

### ISSUE THREAD

**Issue by SammBrooks** [neonbjb/tortoise-tts#763]
Hope ya'll can bear with me here. I'm not a dev, just someone working in production. So something might just be going over my head here.

I installed as directed on the main git page.
When I tried to gen I got this:

`ImportError: tokenizers>=0.11.1,!=0.11.3,<0.14 is required for a normal functioning of this module, but found tokenizers==0.15.1.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main`

So before trying the suggestion there I ran the optional command for windows in case that was somehow at fault:

`conda install -c conda-forge pysoundfile`

Didn't solve the problem, kept getting the same error.
So I ran the suggested fix:

`pip install transformers -U`

and was given:

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tortoise-tts 3.0.0 requires transformers==4.31.0, but you have transformers 4.40.1 which is incompatible.`

So. Assuming that it, in fact, *did* require `transformers==4.31.0` I re-ran the command with the extra information.
Now I'm getting this:

`Traceback (most recent call last):
  File "C:\Users\USER\tortoise-tts\tortoise\do_tts.py", line 7, in <module>
    from api import TextToSpeech, MODELS_DIR
  File "C:\Users\USER\tortoise-tts\tortoise\api.py", line 17, in <module>
    from tortoise.models.clvp import CLVP
  File "C:\Users\USER\miniconda3\envs\tortoise\lib\site-packages\tortoise_tts-3.0.0-py3.9.egg\tortoise\models\clvp.py", line 7, in <module>
    from tortoise.models.transformer import Transformer
  File "C:\Users\USER\miniconda3\envs\tortoise\lib\site-packages\tortoise_tts-3.0.0-py3.9.egg\tortoise\models\transformer.py", line 6, in <module>
    from rotary_embedding_torch import RotaryEmbedding
  File "C:\Users\USER\miniconda3\envs\tortoise\lib\site-packages\rotary_embedding_torch-0.5.3-py3.9.egg\rotary_embedding_torch\__init__.py", line 1, in <module>
    from rotary_embedding_torch.rotary_embedding_torch import (
  File "C:\Users\USER\miniconda3\envs\tortoise\lib\site-packages\rotary_embedding_torch-0.5.3-py3.9.egg\rotary_embedding_torch\rotary_embedding_torch.py", line 10, in <module>
    from beartype import beartype
ModuleNotFoundError: No module named 'beartype'`

I'm at a total loss. Wtf is "beartype", and can I use an AR-15 on it if 50 of them come charging into my yard while my kids are out playing?

But unironically, what's the deal here?

I've tried the same steps on both Python 3.9 (implied by `conda create --name tortoise python=3.9 numba inflect`), and the latest build. Plus both Anaconda and Miniconda. 
Every time I end up somewhere aproximately here.

Any help that a base-line nerd that just likes using open-source programs could understand would be greatly appreciated.

**Comment by cracktorio** [comment]
i had the exact same problem following the exact same steps you did. [Here's](https://pastebin.com/raw/P63VmMK8) my cmd output after freshly installing the program.

**Comment by HppyDedPxl** [comment]
I was running into the same issue today. I managed to fix it by installing remaining dependencies manually.

With your conda environment active:
`pip install -U beartype`
`pip install -v "librosa==0.10.1"`
`pip install -U lazy_loader`

Does not solve the core issue but it allowed me to run do_tts.py. I don't know if the entire project will work however I will do some more testing over the next days as it is getting late.
