### ISSUE TITLE
cant install couldnt find scipy.tar.gz

### ISSUE THREAD

**Issue by YousefMohamed101** [neonbjb/tortoise-tts#792]
Hey guys i try to install i followed the steps but i get this error.

error: Couldn't find a setup script in C:\Users\PC\AppData\Local\Temp\easy_install-idorpf4c\scipy-1.14.0rc1.tar.gz

**Comment by robinstn** [comment]
I have the same issue
Downloading https://files.pythonhosted.org/packages/a1/ee/e1023e41c2c9f9ac7b9d2bafd445b6036d2a2226000028c8c3202eee5234/scipy-1.14.0rc1.tar.gz#sha256=1e04538267216e6e4e738514c0f2ce01a811e97aa9bc1982d35be91aa055f384
Best match: scipy 1.14.0rc1
Processing scipy-1.14.0rc1.tar.gz
error: Couldn't find a setup script in C:\Users\MyPC\AppData\Local\Temp\easy_install-jf58hedo\scipy-1.14.0rc1.tar.gz

**Comment by jason-c-kwan** [comment]
I think I figured out how to fix this. What you do is to edit `setup.py`. Look for this block:

```python
    install_requires=[
        'tqdm',
        'rotary_embedding_torch',
        'inflect',
        'progressbar',
        'einops',
        'unidecode',
        'scipy',
        'librosa',
        'transformers==4.31.0',
        'tokenizers',
        # 'deepspeed==0.8.3',
    ],
```

and change it so that now we specify the latest non-release candidate of scipy:

```python
    install_requires=[
        'tqdm',
        'rotary_embedding_torch',
        'inflect',
        'progressbar',
        'einops',
        'unidecode',
        'scipy==1.13.1',
        'librosa',
        'transformers==4.31.0',
        'tokenizers',
        # 'deepspeed==0.8.3',
    ],
```

Although, I did test this on linux, and it seems like you guys are using Windows. I was getting the same error, though.

**Comment by vootox** [comment]
> I think I figured out how to fix this. What you do is to edit `setup.py`. Look for this block:
> 
> ```python
>     install_requires=[
>         'tqdm',
>         'rotary_embedding_torch',
>         'inflect',
>         'progressbar',
>         'einops',
>         'unidecode',
>         'scipy',
>         'librosa',
>         'transformers==4.31.0',
>         'tokenizers',
>         # 'deepspeed==0.8.3',
>     ],
> ```
> 
> and change it so that now we specify the latest non-release candidate of scipy:
> 
> ```python
>     install_requires=[
>         'tqdm',
>         'rotary_embedding_torch',
>         'inflect',
>         'progressbar',
>         'einops',
>         'unidecode',
>         'scipy==1.13.1',
>         'librosa',
>         'transformers==4.31.0',
>         'tokenizers',
>         # 'deepspeed==0.8.3',
>     ],
> ```
> 
> Although, I did test this on linux, and it seems like you guys are using Windows. I was getting the same error, though.

I'm on Windows and this worked for me too, thanks for posting.

**Comment by YousefMohamed101** [comment]
> I think I figured out how to fix this. What you do is to edit `setup.py`. Look for this block:
> 
> ```python
>     install_requires=[
>         'tqdm',
>         'rotary_embedding_torch',
>         'inflect',
>         'progressbar',
>         'einops',
>         'unidecode',
>         'scipy',
>         'librosa',
>         'transformers==4.31.0',
>         'tokenizers',
>         # 'deepspeed==0.8.3',
>     ],
> ```
> 
> and change it so that now we specify the latest non-release candidate of scipy:
> 
> ```python
>     install_requires=[
>         'tqdm',
>         'rotary_embedding_torch',
>         'inflect',
>         'progressbar',
>         'einops',
>         'unidecode',
>         'scipy==1.13.1',
>         'librosa',
>         'transformers==4.31.0',
>         'tokenizers',
>         # 'deepspeed==0.8.3',
>     ],
> ```
> 
> Although, I did test this on linux, and it seems like you guys are using Windows. I was getting the same error, though.

this worked for me thank you very much

**Comment by Xeraster** [comment]
This solved the spicy error for me but now I have a new error:
```
Processing dependencies for tortoise-tts==3.0.0
error: tokenizers 0.15.1 is installed but tokenizers!=0.11.3,<0.14,>=0.11.1 is required by {'transformers'}
```

**Comment by mardoyyy** [comment]
> This solved the spicy error for me but now I have a new error:
> 
> ```
> Processing dependencies for tortoise-tts==3.0.0
> error: tokenizers 0.15.1 is installed but tokenizers!=0.11.3,<0.14,>=0.11.1 is required by {'transformers'}
> ```
> 
> I changed "tokenizers" to "tokenizers==0.11.1". The installation finally finishes but the program doesn't actually work. For example if I try "python tortoise/socket_server.py ", I get the following output:
> 
> ```
> Traceback (most recent call last):
>   File "/media/hdd/documents_hdd/tortise-tts/tortoise-tts/tortoise/socket_server.py", line 1, in <module>
>     import spacy
> ModuleNotFoundError: No module named 'spacy'
> ```
> 
> so then I tried adding: 'spacy', to my setup.py file. Now I get this:
> 
> ```
> File "/media/hdd/documents_hdd/tortise-tts/tortoise-tts/tortoise/socket_server.py", line 4, in <module>
>     from tortoise.api_fast import TextToSpeech
>   File "/home/scott/miniconda3/envs/tortoise/lib/python3.9/site-packages/tortoise_tts-3.0.0-py3.9.egg/tortoise/api_fast.py", line 14, in <module>
>     from tortoise.models.autoregressive import UnifiedVoice
>   File "/home/scott/miniconda3/envs/tortoise/lib/python3.9/site-packages/tortoise_tts-3.0.0-py3.9.egg/tortoise/models/autoregressive.py", line 6, in <module>
>     from transformers import GPT2Config, GPT2PreTrainedModel, LogitsProcessorList
>   File "/home/scott/miniconda3/envs/tortoise/lib/python3.9/site-packages/transformers/__init__.py", line 26, in <module>
>     from . import dependency_versions_check
>   File "/home/scott/miniconda3/envs/tortoise/lib/python3.9/site-packages/transformers/dependency_versions_check.py", line 41, in <module>
>     require_version_core(deps[pkg])
>   File "/home/scott/miniconda3/envs/tortoise/lib/python3.9/site-packages/transformers/utils/versions.py", line 123, in require_version_core
>     return require_version(requirement, hint)
>   File "/home/scott/miniconda3/envs/tortoise/lib/python3.9/site-packages/transformers/utils/versions.py", line 117, in require_version
>     _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
>   File "/home/scott/miniconda3/envs/tortoise/lib/python3.9/site-packages/transformers/utils/versions.py", line 50, in _compare_versions
>     raise ImportError(
> ImportError: tokenizers>=0.11.1,!=0.11.3,<0.14 is required for a normal functioning of this module, but found tokenizers==0.15.1.
> Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
> ```
> 
> Does anybody know how to fix this? How do I manually uninstall tokenizers 15? Where are those files stored? Can I manually installed these dependencies in conda? "pip install [package]" doesn't work.

just run this man

`pip install tokenizers==0.11.1`

hope you'll good

**Comment by rose07** [comment]
https://tts.byylook.com/ai/text-to-speech

**Comment by haydonryan** [comment]
> I think I figured out how to fix this. What you do is to edit `setup.py`. Look for this block:
> 
> ```python
>     install_requires=[
>         'tqdm',
>         'rotary_embedding_torch',
>         'inflect',
>         'progressbar',
>         'einops',
>         'unidecode',
>         'scipy',
>         'librosa',
>         'transformers==4.31.0',
>         'tokenizers',
>         # 'deepspeed==0.8.3',
>     ],
> ```
> 
> and change it so that now we specify the latest non-release candidate of scipy:
> 
> ```python
>     install_requires=[
>         'tqdm',
>         'rotary_embedding_torch',
>         'inflect',
>         'progressbar',
>         'einops',
>         'unidecode',
>         'scipy==1.13.1',
>         'librosa',
>         'transformers==4.31.0',
>         'tokenizers',
>         # 'deepspeed==0.8.3',
>     ],
> ```
> 
> Although, I did test this on linux, and it seems like you guys are using Windows. I was getting the same error, though.

Unfortunately I still get the same error even after pinning to 1.13.1....
```
Python 3.8
conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia
```

```
Installed /home/haydon/.conda/envs/tortoise/lib/python3.8/site-packages/tortoise_tts-3.0.0-py3.8.egg
Processing dependencies for tortoise-tts==3.0.0
Searching for scipy==1.13.1
Reading https://pypi.org/simple/scipy/
Downloading https://files.pythonhosted.org/packages/ae/00/48c2f661e2816ccf2ecd77982f6605b2950afe60f60a52b4cbbc2504aa8f/scipy-1.13.1.tar.gz#sha256=095a87a0312b08dfd6a6155cbbd310a8c51800fc931b8c0b84003014b874ed3c
Best match: scipy 1.13.1
Processing scipy-1.13.1.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-4j_3krrx/scipy-1.13.1.tar.gz
```
