### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by planetrocke** [neonbjb/tortoise-tts#81]
I have what I thought was a working set up on Ubuntu 20.04... but when I ran do_tts.py with the sample line in the readme, I received this:

Traceback (most recent call last):
  File "tortoise/do_tts.py", line 27, in <module>
    tts = TextToSpeech(models_dir=args.model_dir)
  File "/home/srocke/tortoise-tts/tortoise/api.py", line 217, in __init__
    self.tokenizer = VoiceBpeTokenizer()
  File "/home/srocke/anaconda3/lib/python3.7/site-packages/TorToiSe-2.4.0-py3.7.egg/tortoise/utils/tokenizer.py", line 175, in __init__
    self.tokenizer = Tokenizer.from_file(vocab_file)
Exception: No such file or directory (os error 2)

I've set up tortoise several times on Windows 10, but when I tried to generate latents using the separate py file, I also received the same error.

**Comment by jnordberg** [comment]
Are you on the latest commit on main? If so what does the following give you:

```py
from tortoise.utils.tokenizer import DEFAULT_VOCAB_FILE
print(DEFAULT_VOCAB_FILE)
```

**Comment by bytosaur** [comment]
hey there,
 
having the same issue on jupyter hub running Ubuntu 20.04.
I have installed pytorch as follows:
```shell
```
