### ISSUE TITLE
Path issue for get_conditioning_latents.py

### ISSUE THREAD

**Issue by planetrocke** [neonbjb/tortoise-tts#83]
@neonbjb Thank you for the "tip" on pulling from the latest commit :) that worked for do_tts.py. The issue I am having now is I can't run:

python3 tortoise/get_conditioning_latents.py --voice /home/srocke/tortoise-tts/tortoise/voices/myself (tried with various paths here)

I am receiving the following:

Traceback (most recent call last):
  File "tortoise/get_conditioning_latents.py", line 20, in <module>
    voices = get_voices()
  File "/home/srocke/anaconda3/lib/python3.7/site-packages/TorToiSe-2.4.1-py3.7.egg/tortoise/utils/audio.py", line 92, in get_voices
    subs = os.listdir(d)
FileNotFoundError: [Errno 2] No such file or directory: '/home/srocke/anaconda3/lib/python3.7/site-packages/TorToiSe-2.4.1-py3.7.egg/tortoise/utils/../voices'

**Comment by planetrocke** [comment]
Update: I was able to get this to work by hard-coding BUILTIN_VOICES_DIR (in audio.py) to the "non-egg" version of tortoise. The voices are not packaged in the egg. I think the voices linkage should point to the install root somehow.

**Comment by planetrocke** [comment]
Thank you. I have a question about this, though. If the voices folder is included in the egg, where do we place custom voices we add ourselves? Is there a best practice for this somewhere I missed?

**Comment by neonbjb** [comment]
Good point. Filed #85 to do this better. For now you'll just have to stick custom voices in the egg directory, manually hack the code, or revert back to 870b2d2fc2b1c35c413e67ad22c0fa426e60605c.
