### ISSUE TITLE
A new error with the latest repo

### ISSUE THREAD

**Issue by RakibRyan** [neonbjb/tortoise-tts#88]
(base) C:\Users\Ryan\tortoise-tts>python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast
Traceback (most recent call last):
  File "C:\Users\Ryan\tortoise-tts\tortoise\do_tts.py", line 37, in <module>
    gen, dbg_state = tts.tts_with_preset(args.text, k=args.candidates, voice_samples=voice_samples, conditioning_latents=conditioning_latents,
  File "C:\Users\Ryan\tortoise-tts\tortoise\api.py", line 325, in tts_with_preset
    return self.tts(text, **settings)
  File "C:\Users\Ryan\tortoise-tts\tortoise\api.py", line 393, in tts
    auto_conditioning, diffusion_conditioning = self.get_random_conditioning_latents()
  File "C:\Users\Ryan\tortoise-tts\tortoise\api.py", line 300, in get_random_conditioning_latents
    self.rlg_diffusion.load_state_dict(torch.load(get_model_path('rlg_diffuser.pth', self.models_dir), map_location=torch.device('cpu')))
  File "D:\Anaconda3\lib\site-packages\torch\serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "D:\Anaconda3\lib\site-packages\torch\serialization.py", line 243, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by neonbjb** [comment]
One of your models is corrupt. Delete the corrupted model file in C:\Users\Ryan\.cache\tortoise (looks like it is probably 'rlg_diffuser.pth') and try again.
